export const countriesList = [
  {
    country: "AC",
    dialCode: "+247",
    exampleNumber: "40123",
    countryName: "Ascension Island",
  },
  {
    country: "AD",
    dialCode: "+376",
    exampleNumber: "312345",
    countryName: "Andorra",
  },
  {
    country: "AE",
    dialCode: "+971",
    exampleNumber: "501234567",
    countryName: "United Arab Emirates",
  },
  {
    country: "AF",
    dialCode: "+93",
    exampleNumber: "701234567",
    countryName: "Afghanistan",
  },
  {
    country: "AG",
    dialCode: "+1",
    exampleNumber: "2684641234",
    countryName: "Antigua and Barbuda",
  },
  {
    country: "AI",
    dialCode: "+1",
    exampleNumber: "2642351234",
    countryName: "Anguilla",
  },
  {
    country: "AL",
    dialCode: "+355",
    exampleNumber: "672123456",
    countryName: "Albania",
  },
  {
    country: "AM",
    dialCode: "+374",
    exampleNumber: "77123456",
    countryName: "Armenia",
  },
  {
    country: "AO",
    dialCode: "+244",
    exampleNumber: "923123456",
    countryName: "Angola",
  },
  {
    country: "AR",
    dialCode: "+54",
    exampleNumber: "91123456789",
    countryName: "Argentina",
  },
  {
    country: "AS",
    dialCode: "+1",
    exampleNumber: "6847331234",
    countryName: "American Samoa",
  },
  {
    country: "AT",
    dialCode: "+43",
    exampleNumber: "664123456",
    countryName: "Austria",
  },
  {
    country: "AU",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Australia",
  },
  {
    country: "AW",
    dialCode: "+297",
    exampleNumber: "5601234",
    countryName: "Aruba",
  },
  {
    country: "AX",
    dialCode: "+358",
    exampleNumber: "412345678",
    countryName: "Åland Islands",
  },
  {
    country: "AZ",
    dialCode: "+994",
    exampleNumber: "401234567",
    countryName: "Azerbaijan",
  },
  {
    country: "BA",
    dialCode: "+387",
    exampleNumber: "61123456",
    countryName: "Bosnia and Herzegovina",
  },
  {
    country: "BB",
    dialCode: "+1",
    exampleNumber: "2462501234",
    countryName: "Barbados",
  },
  {
    country: "BD",
    dialCode: "+880",
    exampleNumber: "1812345678",
    countryName: "Bangladesh",
  },
  {
    country: "BE",
    dialCode: "+32",
    exampleNumber: "470123456",
    countryName: "Belgium",
  },
  {
    country: "BF",
    dialCode: "+226",
    exampleNumber: "70123456",
    countryName: "Burkina Faso",
  },
  {
    country: "BG",
    dialCode: "+359",
    exampleNumber: "43012345",
    countryName: "Bulgaria",
  },
  {
    country: "BH",
    dialCode: "+973",
    exampleNumber: "36001234",
    countryName: "Bahrain",
  },
  {
    country: "BI",
    dialCode: "+257",
    exampleNumber: "79561234",
    countryName: "Burundi",
  },
  {
    country: "BJ",
    dialCode: "+229",
    exampleNumber: "0195123456",
    countryName: "Benin",
  },
  {
    country: "BL",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Saint Martin",
  },
  {
    country: "BM",
    dialCode: "+1",
    exampleNumber: "4413701234",
    countryName: "Bermuda",
  },
  {
    country: "BN",
    dialCode: "+673",
    exampleNumber: "7123456",
    countryName: "Brunei Darussalam",
  },
  {
    country: "BO",
    dialCode: "+591",
    exampleNumber: "71234567",
    countryName: "Bolivia",
  },
  {
    country: "BQ",
    dialCode: "+599",
    exampleNumber: "3181234",
    countryName: "Bonaire",
  },
  {
    country: "BR",
    dialCode: "+55",
    exampleNumber: "11961234567",
    countryName: "Brazil",
  },
  {
    country: "BS",
    dialCode: "+1",
    exampleNumber: "2423591234",
    countryName: "Bahamas",
  },
  {
    country: "BT",
    dialCode: "+975",
    exampleNumber: "17123456",
    countryName: "Bhutan",
  },
  {
    country: "BW",
    dialCode: "+267",
    exampleNumber: "71123456",
    countryName: "Botswana",
  },
  {
    country: "BY",
    dialCode: "+375",
    exampleNumber: "294911911",
    countryName: "Belarus",
  },
  {
    country: "BZ",
    dialCode: "+501",
    exampleNumber: "6221234",
    countryName: "Belize",
  },
  {
    country: "CA",
    dialCode: "+1",
    exampleNumber: "5062345678",
    countryName: "Canada",
  },
  {
    country: "CC",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Cocos (Keeling) Islands",
  },
  {
    country: "CD",
    dialCode: "+243",
    exampleNumber: "991234567",
    countryName: "Congo, The Democratic Republic of the",
  },
  {
    country: "CF",
    dialCode: "+236",
    exampleNumber: "70012345",
    countryName: "Central African Republic",
  },
  {
    country: "CG",
    dialCode: "+242",
    exampleNumber: "061234567",
    countryName: "Congo",
  },
  {
    country: "CH",
    dialCode: "+41",
    exampleNumber: "781234567",
    countryName: "Switzerland",
  },
  {
    country: "CI",
    dialCode: "+225",
    exampleNumber: "0123456789",
    countryName: "Cote D&apos;Ivoire",
  },
  {
    country: "CK",
    dialCode: "+682",
    exampleNumber: "71234",
    countryName: "Cook Islands",
  },
  {
    country: "CL",
    dialCode: "+56",
    exampleNumber: "221234567",
    countryName: "Chile",
  },
  {
    country: "CM",
    dialCode: "+237",
    exampleNumber: "671234567",
    countryName: "Cameroon",
  },
  {
    country: "CN",
    dialCode: "+86",
    exampleNumber: "13123456789",
    countryName: "China",
  },
  {
    country: "CO",
    dialCode: "+57",
    exampleNumber: "3211234567",
    countryName: "Colombia",
  },
  {
    country: "CR",
    dialCode: "+506",
    exampleNumber: "83123456",
    countryName: "Costa Rica",
  },
  {
    country: "CU",
    dialCode: "+53",
    exampleNumber: "51234567",
    countryName: "Cuba",
  },
  {
    country: "CV",
    dialCode: "+238",
    exampleNumber: "9911234",
    countryName: "Cape Verde",
  },
  {
    country: "CW",
    dialCode: "+599",
    exampleNumber: "95181234",
    countryName: "Caribbean Netherlands",
  },
  {
    country: "CX",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Christmas Island",
  },
  {
    country: "CY",
    dialCode: "+357",
    exampleNumber: "96123456",
    countryName: "Cyprus",
  },
  {
    country: "CZ",
    dialCode: "+420",
    exampleNumber: "601123456",
    countryName: "Czech Republic",
  },
  {
    country: "DE",
    dialCode: "+49",
    exampleNumber: "15123456789",
    countryName: "Germany",
  },
  {
    country: "DJ",
    dialCode: "+253",
    exampleNumber: "77831001",
    countryName: "Djibouti",
  },
  {
    country: "DK",
    dialCode: "+45",
    exampleNumber: "34412345",
    countryName: "Denmark",
  },
  {
    country: "DM",
    dialCode: "+1",
    exampleNumber: "7672251234",
    countryName: "Dominica",
  },
  {
    country: "DO",
    dialCode: "+1",
    exampleNumber: "8092345678",
    countryName: "Dominican Republic",
  },
  {
    country: "DZ",
    dialCode: "+213",
    exampleNumber: "551234567",
    countryName: "Algeria",
  },
  {
    country: "EC",
    dialCode: "+593",
    exampleNumber: "991234567",
    countryName: "Ecuador",
  },
  {
    country: "EE",
    dialCode: "+372",
    exampleNumber: "51234567",
    countryName: "Estonia",
  },
  {
    country: "EG",
    dialCode: "+20",
    exampleNumber: "1001234567",
    countryName: "Egypt",
  },
  {
    country: "EH",
    dialCode: "+212",
    exampleNumber: "650123456",
    countryName: "Western Sahara",
  },
  {
    country: "ER",
    dialCode: "+291",
    exampleNumber: "7123456",
    countryName: "Eritrea",
  },
  {
    country: "ES",
    dialCode: "+34",
    exampleNumber: "612345678",
    countryName: "Spain",
  },
  {
    country: "ET",
    dialCode: "+251",
    exampleNumber: "911234567",
    countryName: "Ethiopia",
  },
  {
    country: "FI",
    dialCode: "+358",
    exampleNumber: "412345678",
    countryName: "Finland",
  },
  {
    country: "FJ",
    dialCode: "+679",
    exampleNumber: "7012345",
    countryName: "Fiji",
  },
  {
    country: "FK",
    dialCode: "+500",
    exampleNumber: "51234",
    countryName: "Falkland Islands (Malvinas)",
  },
  {
    country: "FM",
    dialCode: "+691",
    exampleNumber: "3501234",
    countryName: "Micronesia, Federated States of",
  },
  {
    country: "FO",
    dialCode: "+298",
    exampleNumber: "211234",
    countryName: "Faroe Islands",
  },
  {
    country: "FR",
    dialCode: "+33",
    exampleNumber: "612345678",
    countryName: "France",
  },
  {
    country: "GA",
    dialCode: "+241",
    exampleNumber: "06031234",
    countryName: "Gabon",
  },
  {
    country: "GB",
    dialCode: "+44",
    exampleNumber: "7400123456",
    countryName: "United Kingdom",
  },
  {
    country: "GD",
    dialCode: "+1",
    exampleNumber: "4734031234",
    countryName: "Grenada",
  },
  {
    country: "GE",
    dialCode: "+995",
    exampleNumber: "555123456",
    countryName: "Georgia",
  },
  {
    country: "GF",
    dialCode: "+594",
    exampleNumber: "694201234",
    countryName: "French Guiana",
  },
  {
    country: "GG",
    dialCode: "+44",
    exampleNumber: "7781123456",
    countryName: "Guernsey",
  },
  {
    country: "GH",
    dialCode: "+233",
    exampleNumber: "231234567",
    countryName: "Ghana",
  },
  {
    country: "GI",
    dialCode: "+350",
    exampleNumber: "57123456",
    countryName: "Gibraltar",
  },
  {
    country: "GL",
    dialCode: "+299",
    exampleNumber: "221234",
    countryName: "Greenland",
  },
  {
    country: "GM",
    dialCode: "+220",
    exampleNumber: "3012345",
    countryName: "Gambia",
  },
  {
    country: "GN",
    dialCode: "+224",
    exampleNumber: "601123456",
    countryName: "Guinea",
  },
  {
    country: "GP",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Guadeloupe",
  },
  {
    country: "GQ",
    dialCode: "+240",
    exampleNumber: "222123456",
    countryName: "Equatorial Guinea",
  },
  {
    country: "GR",
    dialCode: "+30",
    exampleNumber: "6912345678",
    countryName: "Greece",
  },
  {
    country: "GT",
    dialCode: "+502",
    exampleNumber: "51234567",
    countryName: "Guatemala",
  },
  {
    country: "GU",
    dialCode: "+1",
    exampleNumber: "6713001234",
    countryName: "Guam",
  },
  {
    country: "GW",
    dialCode: "+245",
    exampleNumber: "955012345",
    countryName: "Guinea-Bissau",
  },
  {
    country: "GY",
    dialCode: "+592",
    exampleNumber: "6091234",
    countryName: "Guyana",
  },
  {
    country: "HK",
    dialCode: "+852",
    exampleNumber: "51234567",
    countryName: "Hong Kong",
  },
  {
    country: "HN",
    dialCode: "+504",
    exampleNumber: "91234567",
    countryName: "Honduras",
  },
  {
    country: "HR",
    dialCode: "+385",
    exampleNumber: "921234567",
    countryName: "Croatia",
  },
  {
    country: "HT",
    dialCode: "+509",
    exampleNumber: "34101234",
    countryName: "Haiti",
  },
  {
    country: "HU",
    dialCode: "+36",
    exampleNumber: "201234567",
    countryName: "Hungary",
  },
  {
    country: "ID",
    dialCode: "+62",
    exampleNumber: "812345678",
    countryName: "Indonesia",
  },
  {
    country: "IE",
    dialCode: "+353",
    exampleNumber: "850123456",
    countryName: "Ireland",
  },
  {
    country: "IL",
    dialCode: "+972",
    exampleNumber: "502345678",
    countryName: "Israel",
  },
  {
    country: "IM",
    dialCode: "+44",
    exampleNumber: "7924123456",
    countryName: "Isle of Man",
  },
  {
    country: "IN",
    dialCode: "+91",
    exampleNumber: "8123456789",
    countryName: "India",
  },
  {
    country: "IO",
    dialCode: "+246",
    exampleNumber: "3801234",
    countryName: "British Indian Ocean Territory",
  },
  {
    country: "IQ",
    dialCode: "+964",
    exampleNumber: "7912345678",
    countryName: "Iraq",
  },
  {
    country: "IR",
    dialCode: "+98",
    exampleNumber: "9123456789",
    countryName: "Iran",
  },
  {
    country: "IS",
    dialCode: "+354",
    exampleNumber: "6111234",
    countryName: "Iceland",
  },
  {
    country: "IT",
    dialCode: "+39",
    exampleNumber: "3123456789",
    countryName: "Italy",
  },
  {
    country: "JE",
    dialCode: "+44",
    exampleNumber: "7797712345",
    countryName: "Jersey",
  },
  {
    country: "JM",
    dialCode: "+1",
    exampleNumber: "8762101234",
    countryName: "Jamaica",
  },
  {
    country: "JO",
    dialCode: "+962",
    exampleNumber: "790123456",
    countryName: "Jordan",
  },
  {
    country: "JP",
    dialCode: "+81",
    exampleNumber: "9012345678",
    countryName: "Japan",
  },
  {
    country: "KE",
    dialCode: "+254",
    exampleNumber: "712123456",
    countryName: "Kenya",
  },
  {
    country: "KG",
    dialCode: "+996",
    exampleNumber: "700123456",
    countryName: "Kyrgyzstan",
  },
  {
    country: "KH",
    dialCode: "+855",
    exampleNumber: "91234567",
    countryName: "Cambodia",
  },
  {
    country: "KI",
    dialCode: "+686",
    exampleNumber: "72001234",
    countryName: "Kiribati",
  },
  {
    country: "KM",
    dialCode: "+269",
    exampleNumber: "3212345",
    countryName: "Comoros",
  },
  {
    country: "KN",
    dialCode: "+1",
    exampleNumber: "8697652917",
    countryName: "Saint Kitts and Nevis",
  },
  {
    country: "KP",
    dialCode: "+850",
    exampleNumber: "1921234567",
    countryName: "Korea, Democratic People&apos;S Republic of",
  },
  {
    country: "KR",
    dialCode: "+82",
    countryName: "South Korea",
  },
  {
    country: "KW",
    dialCode: "+965",
    exampleNumber: "50012345",
    countryName: "Kuwait",
  },
  {
    country: "KY",
    dialCode: "+1",
    exampleNumber: "3453231234",
    countryName: "Cayman Islands",
  },
  {
    country: "KZ",
    dialCode: "+7",
    exampleNumber: "7710009998",
    countryName: "Kazakhstan",
  },
  {
    country: "LA",
    dialCode: "+856",
    exampleNumber: "2023123456",
    countryName: "Lao People&apos;S Democratic Republic",
  },
  {
    country: "LB",
    dialCode: "+961",
    exampleNumber: "71123456",
    countryName: "Lebanon",
  },
  {
    country: "LC",
    dialCode: "+1",
    exampleNumber: "7582845678",
    countryName: "Saint Lucia",
  },
  {
    country: "LI",
    dialCode: "+423",
    exampleNumber: "660234567",
    countryName: "Liechtenstein",
  },
  {
    country: "LK",
    dialCode: "+94",
    exampleNumber: "712345678",
    countryName: "Sri Lanka",
  },
  {
    country: "LR",
    dialCode: "+231",
    exampleNumber: "770123456",
    countryName: "Liberia",
  },
  {
    country: "LS",
    dialCode: "+266",
    exampleNumber: "50123456",
    countryName: "Lesotho",
  },
  {
    country: "LT",
    dialCode: "+370",
    exampleNumber: "61234567",
    countryName: "Lithuania",
  },
  {
    country: "LU",
    dialCode: "+352",
    exampleNumber: "628123456",
    countryName: "Luxembourg",
  },
  {
    country: "LV",
    dialCode: "+371",
    exampleNumber: "21234567",
    countryName: "Latvia",
  },
  {
    country: "LY",
    dialCode: "+218",
    exampleNumber: "912345678",
    countryName: "Libyan Arab Jamahiriya",
  },
  {
    country: "MA",
    dialCode: "+212",
    exampleNumber: "650123456",
    countryName: "Morocco",
  },
  {
    country: "MC",
    dialCode: "+377",
    exampleNumber: "612345678",
    countryName: "Monaco",
  },
  {
    country: "MD",
    dialCode: "+373",
    exampleNumber: "62112345",
    countryName: "Moldova, Republic of",
  },
  {
    country: "ME",
    dialCode: "+382",
    exampleNumber: "67622901",
    countryName: "Montenegro",
  },
  {
    country: "MF",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Saint-Barthélemy",
  },
  {
    country: "MG",
    dialCode: "+261",
    exampleNumber: "321234567",
    countryName: "Madagascar",
  },
  {
    country: "MH",
    dialCode: "+692",
    exampleNumber: "2351234",
    countryName: "Marshall Islands",
  },
  {
    country: "MK",
    dialCode: "+389",
    exampleNumber: "72345678",
    countryName: "Macedonia, The Former Yugoslav Republic of",
  },
  {
    country: "ML",
    dialCode: "+223",
    exampleNumber: "65012345",
    countryName: "Mali",
  },
  {
    country: "MM",
    dialCode: "+95",
    exampleNumber: "92123456",
    countryName: "Myanmar",
  },
  {
    country: "MN",
    dialCode: "+976",
    exampleNumber: "88123456",
    countryName: "Mongolia",
  },
  {
    country: "MO",
    dialCode: "+853",
    exampleNumber: "66123456",
    countryName: "Macao",
  },
  {
    country: "MP",
    dialCode: "+1",
    exampleNumber: "6702345678",
    countryName: "Northern Mariana Islands",
  },
  {
    country: "MQ",
    dialCode: "+596",
    exampleNumber: "696201234",
    countryName: "Martinique",
  },
  {
    country: "MR",
    dialCode: "+222",
    exampleNumber: "22123456",
    countryName: "Mauritania",
  },
  {
    country: "MS",
    dialCode: "+1",
    exampleNumber: "6644923456",
    countryName: "Montserrat",
  },
  {
    country: "MT",
    dialCode: "+356",
    exampleNumber: "96961234",
    countryName: "Malta",
  },
  {
    country: "MU",
    dialCode: "+230",
    exampleNumber: "52512345",
    countryName: "Mauritius",
  },
  {
    country: "MV",
    dialCode: "+960",
    exampleNumber: "7712345",
    countryName: "Maldives",
  },
  {
    country: "MW",
    dialCode: "+265",
    exampleNumber: "991234567",
    countryName: "Malawi",
  },
  {
    country: "MX",
    dialCode: "+52",
    exampleNumber: "2221234567",
    countryName: "Mexico",
  },
  {
    country: "MY",
    dialCode: "+60",
    exampleNumber: "123456789",
    countryName: "Malaysia",
  },
  {
    country: "MZ",
    dialCode: "+258",
    exampleNumber: "821234567",
    countryName: "Mozambique",
  },
  {
    country: "NA",
    dialCode: "+264",
    exampleNumber: "811234567",
    countryName: "Namibia",
  },
  {
    country: "NC",
    dialCode: "+687",
    exampleNumber: "751234",
    countryName: "New Caledonia",
  },
  {
    country: "NE",
    dialCode: "+227",
    exampleNumber: "93123456",
    countryName: "Niger",
  },
  {
    country: "NF",
    dialCode: "+672",
    exampleNumber: "381234",
    countryName: "Norfolk Island",
  },
  {
    country: "NG",
    dialCode: "+234",
    exampleNumber: "8021234567",
    countryName: "Nigeria",
  },
  {
    country: "NI",
    dialCode: "+505",
    exampleNumber: "81234567",
    countryName: "Nicaragua",
  },
  {
    country: "NL",
    dialCode: "+31",
    exampleNumber: "612345678",
    countryName: "Netherlands",
  },
  {
    country: "NO",
    dialCode: "+47",
    exampleNumber: "40612345",
    countryName: "Norway",
  },
  {
    country: "NP",
    dialCode: "+977",
    exampleNumber: "9841234567",
    countryName: "Nepal",
  },
  {
    country: "NR",
    dialCode: "+674",
    exampleNumber: "5551234",
    countryName: "Nauru",
  },
  {
    country: "NU",
    dialCode: "+683",
    exampleNumber: "8884012",
    countryName: "Niue",
  },
  {
    country: "NZ",
    dialCode: "+64",
    exampleNumber: "211234567",
    countryName: "New Zealand",
  },
  {
    country: "OM",
    dialCode: "+968",
    exampleNumber: "92123456",
    countryName: "Oman",
  },
  {
    country: "PA",
    dialCode: "+507",
    exampleNumber: "61234567",
    countryName: "Panama",
  },
  {
    country: "PE",
    dialCode: "+51",
    exampleNumber: "912345678",
    countryName: "Peru",
  },
  {
    country: "PF",
    dialCode: "+689",
    exampleNumber: "87123456",
    countryName: "French Polynesia",
  },
  {
    country: "PG",
    dialCode: "+675",
    exampleNumber: "70123456",
    countryName: "Papua New Guinea",
  },
  {
    country: "PH",
    dialCode: "+63",
    exampleNumber: "9051234567",
    countryName: "Philippines",
  },
  {
    country: "PK",
    dialCode: "+92",
    exampleNumber: "3012345678",
    countryName: "Pakistan",
  },
  {
    country: "PL",
    dialCode: "+48",
    exampleNumber: "512345678",
    countryName: "Poland",
  },
  {
    country: "PM",
    dialCode: "+508",
    exampleNumber: "551234",
    countryName: "Saint Pierre and Miquelon",
  },
  {
    country: "PR",
    dialCode: "+1",
    exampleNumber: "7872345678",
    countryName: "Puerto Rico ",
  },
  {
    country: "PS",
    dialCode: "+970",
    exampleNumber: "599123456",
    countryName: "Palestinian Territory, Occupied",
  },
  {
    country: "PT",
    dialCode: "+351",
    exampleNumber: "912345678",
    countryName: "Portugal",
  },
  {
    country: "PW",
    dialCode: "+680",
    exampleNumber: "6201234",
    countryName: "Palau",
  },
  {
    country: "PY",
    dialCode: "+595",
    exampleNumber: "961456789",
    countryName: "Paraguay",
  },
  {
    country: "QA",
    dialCode: "+974",
    exampleNumber: "33123456",
    countryName: "Qatar",
  },
  {
    country: "RE",
    dialCode: "+262",
    exampleNumber: "692123456",
    countryName: "Reunion",
  },
  {
    country: "RO",
    dialCode: "+40",
    exampleNumber: "712034567",
    countryName: "Romania",
  },
  {
    country: "RS",
    dialCode: "+381",
    exampleNumber: "601234567",
    countryName: "Serbia",
  },
  {
    country: "RU",
    dialCode: "+7",
    exampleNumber: "9123456789",
    countryName: "Russian Federation",
  },
  {
    country: "RW",
    dialCode: "+250",
    exampleNumber: "720123456",
    countryName: "RWANDA",
  },
  {
    country: "SA",
    dialCode: "+966",
    exampleNumber: "512345678",
    countryName: "Saudi Arabia",
  },
  {
    country: "SB",
    dialCode: "+677",
    exampleNumber: "7421234",
    countryName: "Solomon Islands",
  },
  {
    country: "SC",
    dialCode: "+248",
    exampleNumber: "2510123",
    countryName: "Seychelles",
  },
  {
    country: "SD",
    dialCode: "+249",
    exampleNumber: "911231234",
    countryName: "Sudan",
  },
  {
    country: "SE",
    dialCode: "+46",
    exampleNumber: "701234567",
    countryName: "Sweden",
  },
  {
    country: "SG",
    dialCode: "+65",
    exampleNumber: "81234567",
    countryName: "Singapore",
  },
  {
    country: "SH",
    dialCode: "+290",
    exampleNumber: "51234",
    countryName: "Saint Helena",
  },
  {
    country: "SI",
    dialCode: "+386",
    exampleNumber: "31234567",
    countryName: "Slovenia",
  },
  {
    country: "SJ",
    dialCode: "+47",
    exampleNumber: "41234567",
    countryName: "Svalbard and Jan Mayen",
  },
  {
    country: "SK",
    dialCode: "+421",
    exampleNumber: "912123456",
    countryName: "Slovakia",
  },
  {
    country: "SL",
    dialCode: "+232",
    exampleNumber: "25123456",
    countryName: "Sierra Leone",
  },
  {
    country: "SM",
    dialCode: "+378",
    exampleNumber: "66661212",
    countryName: "San Marino",
  },
  {
    country: "SN",
    dialCode: "+221",
    exampleNumber: "701234567",
    countryName: "Senegal",
  },
  {
    country: "SO",
    dialCode: "+252",
    exampleNumber: "71123456",
    countryName: "Somalia",
  },
  {
    country: "SR",
    dialCode: "+597",
    exampleNumber: "7412345",
    countryName: "Surikey:1,name",
  },
  {
    country: "SS",
    dialCode: "+211",
    exampleNumber: "977123456",
    countryName: "South Sudan",
  },
  {
    country: "ST",
    dialCode: "+239",
    exampleNumber: "9812345",
    countryName: "Sao Tome and Principe",
  },
  {
    country: "SV",
    dialCode: "+503",
    exampleNumber: "70123456",
    countryName: "El Salvador",
  },
  {
    country: "SX",
    dialCode: "+1",
    exampleNumber: "7215205678",
    countryName: "Sint Maarten ",
  },
  {
    country: "SY",
    dialCode: "+963",
    exampleNumber: "944567890",
    countryName: "Syrian Arab Republic",
  },
  {
    country: "SZ",
    dialCode: "+268",
    exampleNumber: "76123456",
    countryName: "Swaziland",
  },
  {
    country: "TA",
    dialCode: "+290",
    exampleNumber: "8999",
    countryName: "Tristan da Cunha",
  },
  {
    country: "TC",
    dialCode: "+1",
    exampleNumber: "6492311234",
    countryName: "Turks and Caicos Islands",
  },
  {
    country: "TD",
    dialCode: "+235",
    exampleNumber: "63012345",
    countryName: "Chad",
  },
  {
    country: "TG",
    dialCode: "+228",
    exampleNumber: "90112345",
    countryName: "Togo",
  },
  {
    country: "TH",
    dialCode: "+66",
    exampleNumber: "812345678",
    countryName: "Thailand",
  },
  {
    country: "TJ",
    dialCode: "+992",
    exampleNumber: "917123456",
    countryName: "Tajikistan",
  },
  {
    country: "TK",
    dialCode: "+690",
    exampleNumber: "7290",
    countryName: "Tokelau",
  },
  {
    country: "TL",
    dialCode: "+670",
    exampleNumber: "77212345",
    countryName: "Timor-Leste",
  },
  {
    country: "TM",
    dialCode: "+993",
    exampleNumber: "66123456",
    countryName: "Turkmenistan",
  },
  {
    country: "TN",
    dialCode: "+216",
    exampleNumber: "20123456",
    countryName: "Tunisia",
  },
  {
    country: "TO",
    dialCode: "+676",
    exampleNumber: "7715123",
    countryName: "Tonga",
  },
  {
    country: "TR",
    dialCode: "+90",
    exampleNumber: "5012345678",
    countryName: "Turkey",
  },
  {
    country: "TT",
    dialCode: "+1",
    exampleNumber: "8682911234",
    countryName: "Trinidad and Tobago",
  },
  {
    country: "TV",
    dialCode: "+688",
    exampleNumber: "901234",
    countryName: "Tuvalu",
  },
  {
    country: "TW",
    dialCode: "+886",
    exampleNumber: "912345678",
    countryName: "Taiwan, Province of China",
  },
  {
    country: "TZ",
    dialCode: "+255",
    exampleNumber: "621234567",
    countryName: "Tanzania, United Republic of",
  },
  {
    country: "UA",
    dialCode: "+380",
    exampleNumber: "501234567",
    countryName: "Ukraine",
  },
  {
    country: "UG",
    dialCode: "+256",
    exampleNumber: "712345678",
    countryName: "Uganda",
  },
  {
    country: "US",
    dialCode: "+1",
    exampleNumber: "2015550123",
    countryName: "United States of America",
  },
  {
    country: "UY",
    dialCode: "+598",
    exampleNumber: "94231234",
    countryName: "Uruguay",
  },
  {
    country: "UZ",
    dialCode: "+998",
    exampleNumber: "912345678",
    countryName: "Uzbekistan",
  },
  {
    country: "VA",
    dialCode: "+39",
    exampleNumber: "3123456789",
    countryName: "Holy See (Vatican City State)",
  },
  {
    country: "VC",
    dialCode: "+1",
    exampleNumber: "7844301234",
    countryName: "Saint Vincent and the Grenadines",
  },
  {
    country: "VE",
    dialCode: "+58",
    exampleNumber: "4121234567",
    countryName: "Venezuela",
  },
  {
    country: "VG",
    dialCode: "+1",
    exampleNumber: "2843001234",
    countryName: "Virgin Islands, British",
  },
  {
    country: "VI",
    dialCode: "+1",
    exampleNumber: "3406421234",
    countryName: "Virgin Islands, U.S.",
  },
  {
    country: "VN",
    dialCode: "+84",
    exampleNumber: "912345678",
    countryName: "Viet Nam",
  },
  {
    country: "VU",
    dialCode: "+678",
    exampleNumber: "5912345",
    countryName: "Vanuatu",
  },
  {
    country: "WF",
    dialCode: "+681",
    exampleNumber: "821234",
    countryName: "Wallis and Futuna",
  },
  {
    country: "WS",
    dialCode: "+685",
    exampleNumber: "7212345",
    countryName: "Samoa",
  },
  {
    country: "XK",
    dialCode: "+383",
    exampleNumber: "43201234",
    countryName: "Kosovo",
  },
  {
    country: "YE",
    dialCode: "+967",
    exampleNumber: "712345678",
    countryName: "Yemen",
  },
  {
    country: "YT",
    dialCode: "+262",
    exampleNumber: "639012345",
    countryName: "Mayotte",
  },
  {
    country: "ZA",
    dialCode: "+27",
    exampleNumber: "711234567",
    countryName: "South Africa",
  },
  {
    country: "ZM",
    dialCode: "+260",
    exampleNumber: "955123456",
    countryName: "Zambia",
  },
  {
    country: "ZW",
    dialCode: "+263",
    exampleNumber: "712345678",
    countryName: "Zimbabwe",
  },
];
export const nationalities = [
  {
    num_code: "4",
    alpha_2_code: "AF",
    alpha_3_code: "AFG",
    en_short_name: "Afghanistan",
    nationality: "Afghan",
  },
  {
    num_code: "248",
    alpha_2_code: "AX",
    alpha_3_code: "ALA",
    en_short_name: "\u00c5land Islands",
    nationality: "\u00c5land Island",
  },
  {
    num_code: "8",
    alpha_2_code: "AL",
    alpha_3_code: "ALB",
    en_short_name: "Albania",
    nationality: "Albanian",
  },
  {
    num_code: "12",
    alpha_2_code: "DZ",
    alpha_3_code: "DZA",
    en_short_name: "Algeria",
    nationality: "Algerian",
  },
  {
    num_code: "16",
    alpha_2_code: "AS",
    alpha_3_code: "ASM",
    en_short_name: "American Samoa",
    nationality: "American Samoan",
  },
  {
    num_code: "20",
    alpha_2_code: "AD",
    alpha_3_code: "AND",
    en_short_name: "Andorra",
    nationality: "Andorran",
  },
  {
    num_code: "24",
    alpha_2_code: "AO",
    alpha_3_code: "AGO",
    en_short_name: "Angola",
    nationality: "Angolan",
  },
  {
    num_code: "660",
    alpha_2_code: "AI",
    alpha_3_code: "AIA",
    en_short_name: "Anguilla",
    nationality: "Anguillan",
  },
  {
    num_code: "10",
    alpha_2_code: "AQ",
    alpha_3_code: "ATA",
    en_short_name: "Antarctica",
    nationality: "Antarctic",
  },
  {
    num_code: "28",
    alpha_2_code: "AG",
    alpha_3_code: "ATG",
    en_short_name: "Antigua and Barbuda",
    nationality: "Antiguan or Barbudan",
  },
  {
    num_code: "32",
    alpha_2_code: "AR",
    alpha_3_code: "ARG",
    en_short_name: "Argentina",
    nationality: "Argentine",
  },
  {
    num_code: "51",
    alpha_2_code: "AM",
    alpha_3_code: "ARM",
    en_short_name: "Armenia",
    nationality: "Armenian",
  },
  {
    num_code: "533",
    alpha_2_code: "AW",
    alpha_3_code: "ABW",
    en_short_name: "Aruba",
    nationality: "Aruban",
  },
  {
    num_code: "36",
    alpha_2_code: "AU",
    alpha_3_code: "AUS",
    en_short_name: "Australia",
    nationality: "Australian",
  },
  {
    num_code: "40",
    alpha_2_code: "AT",
    alpha_3_code: "AUT",
    en_short_name: "Austria",
    nationality: "Austrian",
  },
  {
    num_code: "31",
    alpha_2_code: "AZ",
    alpha_3_code: "AZE",
    en_short_name: "Azerbaijan",
    nationality: "Azerbaijani, Azeri",
  },
  {
    num_code: "44",
    alpha_2_code: "BS",
    alpha_3_code: "BHS",
    en_short_name: "Bahamas",
    nationality: "Bahamian",
  },
  {
    num_code: "48",
    alpha_2_code: "BH",
    alpha_3_code: "BHR",
    en_short_name: "Bahrain",
    nationality: "Bahraini",
  },
  {
    num_code: "50",
    alpha_2_code: "BD",
    alpha_3_code: "BGD",
    en_short_name: "Bangladesh",
    nationality: "Bangladeshi",
  },
  {
    num_code: "52",
    alpha_2_code: "BB",
    alpha_3_code: "BRB",
    en_short_name: "Barbados",
    nationality: "Barbadian",
  },
  {
    num_code: "112",
    alpha_2_code: "BY",
    alpha_3_code: "BLR",
    en_short_name: "Belarus",
    nationality: "Belarusian",
  },
  {
    num_code: "56",
    alpha_2_code: "BE",
    alpha_3_code: "BEL",
    en_short_name: "Belgium",
    nationality: "Belgian",
  },
  {
    num_code: "84",
    alpha_2_code: "BZ",
    alpha_3_code: "BLZ",
    en_short_name: "Belize",
    nationality: "Belizean",
  },
  {
    num_code: "204",
    alpha_2_code: "BJ",
    alpha_3_code: "BEN",
    en_short_name: "Benin",
    nationality: "Beninese, Beninois",
  },
  {
    num_code: "60",
    alpha_2_code: "BM",
    alpha_3_code: "BMU",
    en_short_name: "Bermuda",
    nationality: "Bermudian, Bermudan",
  },
  {
    num_code: "64",
    alpha_2_code: "BT",
    alpha_3_code: "BTN",
    en_short_name: "Bhutan",
    nationality: "Bhutanese",
  },
  {
    num_code: "68",
    alpha_2_code: "BO",
    alpha_3_code: "BOL",
    en_short_name: "Bolivia (Plurinational State of)",
    nationality: "Bolivian",
  },
  {
    num_code: "535",
    alpha_2_code: "BQ",
    alpha_3_code: "BES",
    en_short_name: "Bonaire, Sint Eustatius and Saba",
    nationality: "Bonaire",
  },
  {
    num_code: "70",
    alpha_2_code: "BA",
    alpha_3_code: "BIH",
    en_short_name: "Bosnia and Herzegovina",
    nationality: "Bosnian or Herzegovinian",
  },
  {
    num_code: "72",
    alpha_2_code: "BW",
    alpha_3_code: "BWA",
    en_short_name: "Botswana",
    nationality: "Motswana, Botswanan",
  },
  {
    num_code: "74",
    alpha_2_code: "BV",
    alpha_3_code: "BVT",
    en_short_name: "Bouvet Island",
    nationality: "Bouvet Island",
  },
  {
    num_code: "76",
    alpha_2_code: "BR",
    alpha_3_code: "BRA",
    en_short_name: "Brazil",
    nationality: "Brazilian",
  },
  {
    num_code: "86",
    alpha_2_code: "IO",
    alpha_3_code: "IOT",
    en_short_name: "British Indian Ocean Territory",
    nationality: "BIOT",
  },
  {
    num_code: "96",
    alpha_2_code: "BN",
    alpha_3_code: "BRN",
    en_short_name: "Brunei Darussalam",
    nationality: "Bruneian",
  },
  {
    num_code: "100",
    alpha_2_code: "BG",
    alpha_3_code: "BGR",
    en_short_name: "Bulgaria",
    nationality: "Bulgarian",
  },
  {
    num_code: "854",
    alpha_2_code: "BF",
    alpha_3_code: "BFA",
    en_short_name: "Burkina Faso",
    nationality: "Burkinab\u00e9",
  },
  {
    num_code: "108",
    alpha_2_code: "BI",
    alpha_3_code: "BDI",
    en_short_name: "Burundi",
    nationality: "Burundian",
  },
  {
    num_code: "132",
    alpha_2_code: "CV",
    alpha_3_code: "CPV",
    en_short_name: "Cabo Verde",
    nationality: "Cabo Verdean",
  },
  {
    num_code: "116",
    alpha_2_code: "KH",
    alpha_3_code: "KHM",
    en_short_name: "Cambodia",
    nationality: "Cambodian",
  },
  {
    num_code: "120",
    alpha_2_code: "CM",
    alpha_3_code: "CMR",
    en_short_name: "Cameroon",
    nationality: "Cameroonian",
  },
  {
    num_code: "124",
    alpha_2_code: "CA",
    alpha_3_code: "CAN",
    en_short_name: "Canada",
    nationality: "Canadian",
  },
  {
    num_code: "136",
    alpha_2_code: "KY",
    alpha_3_code: "CYM",
    en_short_name: "Cayman Islands",
    nationality: "Caymanian",
  },
  {
    num_code: "140",
    alpha_2_code: "CF",
    alpha_3_code: "CAF",
    en_short_name: "Central African Republic",
    nationality: "Central African",
  },
  {
    num_code: "148",
    alpha_2_code: "TD",
    alpha_3_code: "TCD",
    en_short_name: "Chad",
    nationality: "Chadian",
  },
  {
    num_code: "152",
    alpha_2_code: "CL",
    alpha_3_code: "CHL",
    en_short_name: "Chile",
    nationality: "Chilean",
  },
  {
    num_code: "156",
    alpha_2_code: "CN",
    alpha_3_code: "CHN",
    en_short_name: "China",
    nationality: "Chinese",
  },
  {
    num_code: "162",
    alpha_2_code: "CX",
    alpha_3_code: "CXR",
    en_short_name: "Christmas Island",
    nationality: "Christmas Island",
  },
  {
    num_code: "166",
    alpha_2_code: "CC",
    alpha_3_code: "CCK",
    en_short_name: "Cocos (Keeling) Islands",
    nationality: "Cocos Island",
  },
  {
    num_code: "170",
    alpha_2_code: "CO",
    alpha_3_code: "COL",
    en_short_name: "Colombia",
    nationality: "Colombian",
  },
  {
    num_code: "174",
    alpha_2_code: "KM",
    alpha_3_code: "COM",
    en_short_name: "Comoros",
    nationality: "Comoran, Comorian",
  },
  {
    num_code: "178",
    alpha_2_code: "CG",
    alpha_3_code: "COG",
    en_short_name: "Congo (Republic of the)",
    nationality: "Congolese",
  },
  {
    num_code: "180",
    alpha_2_code: "CD",
    alpha_3_code: "COD",
    en_short_name: "Congo (Democratic Republic of the)",
    nationality: "Congolese",
  },
  {
    num_code: "184",
    alpha_2_code: "CK",
    alpha_3_code: "COK",
    en_short_name: "Cook Islands",
    nationality: "Cook Island",
  },
  {
    num_code: "188",
    alpha_2_code: "CR",
    alpha_3_code: "CRI",
    en_short_name: "Costa Rica",
    nationality: "Costa Rican",
  },
  {
    num_code: "384",
    alpha_2_code: "CI",
    alpha_3_code: "CIV",
    en_short_name: "C\u00f4te d&apos;Ivoire",
    nationality: "Ivorian",
  },
  {
    num_code: "191",
    alpha_2_code: "HR",
    alpha_3_code: "HRV",
    en_short_name: "Croatia",
    nationality: "Croatian",
  },
  {
    num_code: "192",
    alpha_2_code: "CU",
    alpha_3_code: "CUB",
    en_short_name: "Cuba",
    nationality: "Cuban",
  },
  {
    num_code: "531",
    alpha_2_code: "CW",
    alpha_3_code: "CUW",
    en_short_name: "Cura\u00e7ao",
    nationality: "Cura\u00e7aoan",
  },
  {
    num_code: "196",
    alpha_2_code: "CY",
    alpha_3_code: "CYP",
    en_short_name: "Cyprus",
    nationality: "Cypriot",
  },
  {
    num_code: "203",
    alpha_2_code: "CZ",
    alpha_3_code: "CZE",
    en_short_name: "Czech Republic",
    nationality: "Czech",
  },
  {
    num_code: "208",
    alpha_2_code: "DK",
    alpha_3_code: "DNK",
    en_short_name: "Denmark",
    nationality: "Danish",
  },
  {
    num_code: "262",
    alpha_2_code: "DJ",
    alpha_3_code: "DJI",
    en_short_name: "Djibouti",
    nationality: "Djiboutian",
  },
  {
    num_code: "212",
    alpha_2_code: "DM",
    alpha_3_code: "DMA",
    en_short_name: "Dominica",
    nationality: "Dominican",
  },
  {
    num_code: "214",
    alpha_2_code: "DO",
    alpha_3_code: "DOM",
    en_short_name: "Dominican Republic",
    nationality: "Dominican",
  },
  {
    num_code: "218",
    alpha_2_code: "EC",
    alpha_3_code: "ECU",
    en_short_name: "Ecuador",
    nationality: "Ecuadorian",
  },
  {
    num_code: "818",
    alpha_2_code: "EG",
    alpha_3_code: "EGY",
    en_short_name: "Egypt",
    nationality: "Egyptian",
  },
  {
    num_code: "222",
    alpha_2_code: "SV",
    alpha_3_code: "SLV",
    en_short_name: "El Salvador",
    nationality: "Salvadoran",
  },
  {
    num_code: "226",
    alpha_2_code: "GQ",
    alpha_3_code: "GNQ",
    en_short_name: "Equatorial Guinea",
    nationality: "Equatorial Guinean, Equatoguinean",
  },
  {
    num_code: "232",
    alpha_2_code: "ER",
    alpha_3_code: "ERI",
    en_short_name: "Eritrea",
    nationality: "Eritrean",
  },
  {
    num_code: "233",
    alpha_2_code: "EE",
    alpha_3_code: "EST",
    en_short_name: "Estonia",
    nationality: "Estonian",
  },
  {
    num_code: "231",
    alpha_2_code: "ET",
    alpha_3_code: "ETH",
    en_short_name: "Ethiopia",
    nationality: "Ethiopian",
  },
  {
    num_code: "238",
    alpha_2_code: "FK",
    alpha_3_code: "FLK",
    en_short_name: "Falkland Islands (Malvinas)",
    nationality: "Falkland Island",
  },
  {
    num_code: "234",
    alpha_2_code: "FO",
    alpha_3_code: "FRO",
    en_short_name: "Faroe Islands",
    nationality: "Faroese",
  },
  {
    num_code: "242",
    alpha_2_code: "FJ",
    alpha_3_code: "FJI",
    en_short_name: "Fiji",
    nationality: "Fijian",
  },
  {
    num_code: "246",
    alpha_2_code: "FI",
    alpha_3_code: "FIN",
    en_short_name: "Finland",
    nationality: "Finnish",
  },
  {
    num_code: "250",
    alpha_2_code: "FR",
    alpha_3_code: "FRA",
    en_short_name: "France",
    nationality: "French",
  },
  {
    num_code: "254",
    alpha_2_code: "GF",
    alpha_3_code: "GUF",
    en_short_name: "French Guiana",
    nationality: "French Guianese",
  },
  {
    num_code: "258",
    alpha_2_code: "PF",
    alpha_3_code: "PYF",
    en_short_name: "French Polynesia",
    nationality: "French Polynesian",
  },
  {
    num_code: "260",
    alpha_2_code: "TF",
    alpha_3_code: "ATF",
    en_short_name: "French Southern Territories",
    nationality: "French Southern Territories",
  },
  {
    num_code: "266",
    alpha_2_code: "GA",
    alpha_3_code: "GAB",
    en_short_name: "Gabon",
    nationality: "Gabonese",
  },
  {
    num_code: "270",
    alpha_2_code: "GM",
    alpha_3_code: "GMB",
    en_short_name: "Gambia",
    nationality: "Gambian",
  },
  {
    num_code: "268",
    alpha_2_code: "GE",
    alpha_3_code: "GEO",
    en_short_name: "Georgia",
    nationality: "Georgian",
  },
  {
    num_code: "276",
    alpha_2_code: "DE",
    alpha_3_code: "DEU",
    en_short_name: "Germany",
    nationality: "German",
  },
  {
    num_code: "288",
    alpha_2_code: "GH",
    alpha_3_code: "GHA",
    en_short_name: "Ghana",
    nationality: "Ghanaian",
  },
  {
    num_code: "292",
    alpha_2_code: "GI",
    alpha_3_code: "GIB",
    en_short_name: "Gibraltar",
    nationality: "Gibraltar",
  },
  {
    num_code: "300",
    alpha_2_code: "GR",
    alpha_3_code: "GRC",
    en_short_name: "Greece",
    nationality: "Greek, Hellenic",
  },
  {
    num_code: "304",
    alpha_2_code: "GL",
    alpha_3_code: "GRL",
    en_short_name: "Greenland",
    nationality: "Greenlandic",
  },
  {
    num_code: "308",
    alpha_2_code: "GD",
    alpha_3_code: "GRD",
    en_short_name: "Grenada",
    nationality: "Grenadian",
  },
  {
    num_code: "312",
    alpha_2_code: "GP",
    alpha_3_code: "GLP",
    en_short_name: "Guadeloupe",
    nationality: "Guadeloupe",
  },
  {
    num_code: "316",
    alpha_2_code: "GU",
    alpha_3_code: "GUM",
    en_short_name: "Guam",
    nationality: "Guamanian, Guambat",
  },
  {
    num_code: "320",
    alpha_2_code: "GT",
    alpha_3_code: "GTM",
    en_short_name: "Guatemala",
    nationality: "Guatemalan",
  },
  {
    num_code: "831",
    alpha_2_code: "GG",
    alpha_3_code: "GGY",
    en_short_name: "Guernsey",
    nationality: "Channel Island",
  },
  {
    num_code: "324",
    alpha_2_code: "GN",
    alpha_3_code: "GIN",
    en_short_name: "Guinea",
    nationality: "Guinean",
  },
  {
    num_code: "624",
    alpha_2_code: "GW",
    alpha_3_code: "GNB",
    en_short_name: "Guinea-Bissau",
    nationality: "Bissau-Guinean",
  },
  {
    num_code: "328",
    alpha_2_code: "GY",
    alpha_3_code: "GUY",
    en_short_name: "Guyana",
    nationality: "Guyanese",
  },
  {
    num_code: "332",
    alpha_2_code: "HT",
    alpha_3_code: "HTI",
    en_short_name: "Haiti",
    nationality: "Haitian",
  },
  {
    num_code: "334",
    alpha_2_code: "HM",
    alpha_3_code: "HMD",
    en_short_name: "Heard Island and McDonald Islands",
    nationality: "Heard Island or McDonald Islands",
  },
  {
    num_code: "336",
    alpha_2_code: "VA",
    alpha_3_code: "VAT",
    en_short_name: "Vatican City State",
    nationality: "Vatican",
  },
  {
    num_code: "340",
    alpha_2_code: "HN",
    alpha_3_code: "HND",
    en_short_name: "Honduras",
    nationality: "Honduran",
  },
  {
    num_code: "344",
    alpha_2_code: "HK",
    alpha_3_code: "HKG",
    en_short_name: "Hong Kong",
    nationality: "Hong Kong, Hong Kongese",
  },
  {
    num_code: "348",
    alpha_2_code: "HU",
    alpha_3_code: "HUN",
    en_short_name: "Hungary",
    nationality: "Hungarian, Magyar",
  },
  {
    num_code: "352",
    alpha_2_code: "IS",
    alpha_3_code: "ISL",
    en_short_name: "Iceland",
    nationality: "Icelandic",
  },
  {
    num_code: "356",
    alpha_2_code: "IN",
    alpha_3_code: "IND",
    en_short_name: "India",
    nationality: "Indian",
  },
  {
    num_code: "360",
    alpha_2_code: "ID",
    alpha_3_code: "IDN",
    en_short_name: "Indonesia",
    nationality: "Indonesian",
  },
  {
    num_code: "364",
    alpha_2_code: "IR",
    alpha_3_code: "IRN",
    en_short_name: "Iran",
    nationality: "Iranian, Persian",
  },
  {
    num_code: "368",
    alpha_2_code: "IQ",
    alpha_3_code: "IRQ",
    en_short_name: "Iraq",
    nationality: "Iraqi",
  },
  {
    num_code: "372",
    alpha_2_code: "IE",
    alpha_3_code: "IRL",
    en_short_name: "Ireland",
    nationality: "Irish",
  },
  {
    num_code: "833",
    alpha_2_code: "IM",
    alpha_3_code: "IMN",
    en_short_name: "Isle of Man",
    nationality: "Manx",
  },
  {
    num_code: "376",
    alpha_2_code: "IL",
    alpha_3_code: "ISR",
    en_short_name: "Israel",
    nationality: "Israeli",
  },
  {
    num_code: "380",
    alpha_2_code: "IT",
    alpha_3_code: "ITA",
    en_short_name: "Italy",
    nationality: "Italian",
  },
  {
    num_code: "388",
    alpha_2_code: "JM",
    alpha_3_code: "JAM",
    en_short_name: "Jamaica",
    nationality: "Jamaican",
  },
  {
    num_code: "392",
    alpha_2_code: "JP",
    alpha_3_code: "JPN",
    en_short_name: "Japan",
    nationality: "Japanese",
  },
  {
    num_code: "832",
    alpha_2_code: "JE",
    alpha_3_code: "JEY",
    en_short_name: "Jersey",
    nationality: "Channel Island",
  },
  {
    num_code: "400",
    alpha_2_code: "JO",
    alpha_3_code: "JOR",
    en_short_name: "Jordan",
    nationality: "Jordanian",
  },
  {
    num_code: "398",
    alpha_2_code: "KZ",
    alpha_3_code: "KAZ",
    en_short_name: "Kazakhstan",
    nationality: "Kazakhstani, Kazakh",
  },
  {
    num_code: "404",
    alpha_2_code: "KE",
    alpha_3_code: "KEN",
    en_short_name: "Kenya",
    nationality: "Kenyan",
  },
  {
    num_code: "296",
    alpha_2_code: "KI",
    alpha_3_code: "KIR",
    en_short_name: "Kiribati",
    nationality: "I-Kiribati",
  },
  {
    num_code: "408",
    alpha_2_code: "KP",
    alpha_3_code: "PRK",
    en_short_name: "Korea (Democratic People's Republic of)",
    nationality: "North Korean",
  },
  {
    num_code: "410",
    alpha_2_code: "KR",
    alpha_3_code: "KOR",
    en_short_name: "Korea (Republic of)",
    nationality: "South Korean",
  },
  {
    num_code: "414",
    alpha_2_code: "KW",
    alpha_3_code: "KWT",
    en_short_name: "Kuwait",
    nationality: "Kuwaiti",
  },
  {
    num_code: "417",
    alpha_2_code: "KG",
    alpha_3_code: "KGZ",
    en_short_name: "Kyrgyzstan",
    nationality: "Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz",
  },
  {
    num_code: "418",
    alpha_2_code: "LA",
    alpha_3_code: "LAO",
    en_short_name: "Lao People&apos;s Democratic Republic",
    nationality: "Lao, Laotian",
  },
  {
    num_code: "428",
    alpha_2_code: "LV",
    alpha_3_code: "LVA",
    en_short_name: "Latvia",
    nationality: "Latvian",
  },
  {
    num_code: "422",
    alpha_2_code: "LB",
    alpha_3_code: "LBN",
    en_short_name: "Lebanon",
    nationality: "Lebanese",
  },
  {
    num_code: "426",
    alpha_2_code: "LS",
    alpha_3_code: "LSO",
    en_short_name: "Lesotho",
    nationality: "Basotho",
  },
  {
    num_code: "430",
    alpha_2_code: "LR",
    alpha_3_code: "LBR",
    en_short_name: "Liberia",
    nationality: "Liberian",
  },
  {
    num_code: "434",
    alpha_2_code: "LY",
    alpha_3_code: "LBY",
    en_short_name: "Libya",
    nationality: "Libyan",
  },
  {
    num_code: "438",
    alpha_2_code: "LI",
    alpha_3_code: "LIE",
    en_short_name: "Liechtenstein",
    nationality: "Liechtenstein",
  },
  {
    num_code: "440",
    alpha_2_code: "LT",
    alpha_3_code: "LTU",
    en_short_name: "Lithuania",
    nationality: "Lithuanian",
  },
  {
    num_code: "442",
    alpha_2_code: "LU",
    alpha_3_code: "LUX",
    en_short_name: "Luxembourg",
    nationality: "Luxembourg, Luxembourgish",
  },
  {
    num_code: "446",
    alpha_2_code: "MO",
    alpha_3_code: "MAC",
    en_short_name: "Macao",
    nationality: "Macanese, Chinese",
  },
  {
    num_code: "807",
    alpha_2_code: "MK",
    alpha_3_code: "MKD",
    en_short_name: "Macedonia (the former Yugoslav Republic of)",
    nationality: "Macedonian",
  },
  {
    num_code: "450",
    alpha_2_code: "MG",
    alpha_3_code: "MDG",
    en_short_name: "Madagascar",
    nationality: "Malagasy",
  },
  {
    num_code: "454",
    alpha_2_code: "MW",
    alpha_3_code: "MWI",
    en_short_name: "Malawi",
    nationality: "Malawian",
  },
  {
    num_code: "458",
    alpha_2_code: "MY",
    alpha_3_code: "MYS",
    en_short_name: "Malaysia",
    nationality: "Malaysian",
  },
  {
    num_code: "462",
    alpha_2_code: "MV",
    alpha_3_code: "MDV",
    en_short_name: "Maldives",
    nationality: "Maldivian",
  },
  {
    num_code: "466",
    alpha_2_code: "ML",
    alpha_3_code: "MLI",
    en_short_name: "Mali",
    nationality: "Malian, Malinese",
  },
  {
    num_code: "470",
    alpha_2_code: "MT",
    alpha_3_code: "MLT",
    en_short_name: "Malta",
    nationality: "Maltese",
  },
  {
    num_code: "584",
    alpha_2_code: "MH",
    alpha_3_code: "MHL",
    en_short_name: "Marshall Islands",
    nationality: "Marshallese",
  },
  {
    num_code: "474",
    alpha_2_code: "MQ",
    alpha_3_code: "MTQ",
    en_short_name: "Martinique",
    nationality: "Martiniquais, Martinican",
  },
  {
    num_code: "478",
    alpha_2_code: "MR",
    alpha_3_code: "MRT",
    en_short_name: "Mauritania",
    nationality: "Mauritanian",
  },
  {
    num_code: "480",
    alpha_2_code: "MU",
    alpha_3_code: "MUS",
    en_short_name: "Mauritius",
    nationality: "Mauritian",
  },
  {
    num_code: "175",
    alpha_2_code: "YT",
    alpha_3_code: "MYT",
    en_short_name: "Mayotte",
    nationality: "Mahoran",
  },
  {
    num_code: "484",
    alpha_2_code: "MX",
    alpha_3_code: "MEX",
    en_short_name: "Mexico",
    nationality: "Mexican",
  },
  {
    num_code: "583",
    alpha_2_code: "FM",
    alpha_3_code: "FSM",
    en_short_name: "Micronesia (Federated States of)",
    nationality: "Micronesian",
  },
  {
    num_code: "498",
    alpha_2_code: "MD",
    alpha_3_code: "MDA",
    en_short_name: "Moldova (Republic of)",
    nationality: "Moldovan",
  },
  {
    num_code: "492",
    alpha_2_code: "MC",
    alpha_3_code: "MCO",
    en_short_name: "Monaco",
    nationality: "Mon\u00e9gasque, Monacan",
  },
  {
    num_code: "496",
    alpha_2_code: "MN",
    alpha_3_code: "MNG",
    en_short_name: "Mongolia",
    nationality: "Mongolian",
  },
  {
    num_code: "499",
    alpha_2_code: "ME",
    alpha_3_code: "MNE",
    en_short_name: "Montenegro",
    nationality: "Montenegrin",
  },
  {
    num_code: "500",
    alpha_2_code: "MS",
    alpha_3_code: "MSR",
    en_short_name: "Montserrat",
    nationality: "Montserratian",
  },
  {
    num_code: "504",
    alpha_2_code: "MA",
    alpha_3_code: "MAR",
    en_short_name: "Morocco",
    nationality: "Moroccan",
  },
  {
    num_code: "508",
    alpha_2_code: "MZ",
    alpha_3_code: "MOZ",
    en_short_name: "Mozambique",
    nationality: "Mozambican",
  },
  {
    num_code: "104",
    alpha_2_code: "MM",
    alpha_3_code: "MMR",
    en_short_name: "Myanmar",
    nationality: "Burmese",
  },
  {
    num_code: "516",
    alpha_2_code: "NA",
    alpha_3_code: "NAM",
    en_short_name: "Namibia",
    nationality: "Namibian",
  },
  {
    num_code: "520",
    alpha_2_code: "NR",
    alpha_3_code: "NRU",
    en_short_name: "Nauru",
    nationality: "Nauruan",
  },
  {
    num_code: "524",
    alpha_2_code: "NP",
    alpha_3_code: "NPL",
    en_short_name: "Nepal",
    nationality: "Nepali, Nepalese",
  },
  {
    num_code: "528",
    alpha_2_code: "NL",
    alpha_3_code: "NLD",
    en_short_name: "Netherlands",
    nationality: "Dutch, Netherlandic",
  },
  {
    num_code: "540",
    alpha_2_code: "NC",
    alpha_3_code: "NCL",
    en_short_name: "New Caledonia",
    nationality: "New Caledonian",
  },
  {
    num_code: "554",
    alpha_2_code: "NZ",
    alpha_3_code: "NZL",
    en_short_name: "New Zealand",
    nationality: "New Zealand, NZ",
  },
  {
    num_code: "558",
    alpha_2_code: "NI",
    alpha_3_code: "NIC",
    en_short_name: "Nicaragua",
    nationality: "Nicaraguan",
  },
  {
    num_code: "562",
    alpha_2_code: "NE",
    alpha_3_code: "NER",
    en_short_name: "Niger",
    nationality: "Nigerien",
  },
  {
    num_code: "566",
    alpha_2_code: "NG",
    alpha_3_code: "NGA",
    en_short_name: "Nigeria",
    nationality: "Nigerian",
  },
  {
    num_code: "570",
    alpha_2_code: "NU",
    alpha_3_code: "NIU",
    en_short_name: "Niue",
    nationality: "Niuean",
  },
  {
    num_code: "574",
    alpha_2_code: "NF",
    alpha_3_code: "NFK",
    en_short_name: "Norfolk Island",
    nationality: "Norfolk Island",
  },
  {
    num_code: "580",
    alpha_2_code: "MP",
    alpha_3_code: "MNP",
    en_short_name: "Northern Mariana Islands",
    nationality: "Northern Marianan",
  },
  {
    num_code: "578",
    alpha_2_code: "NO",
    alpha_3_code: "NOR",
    en_short_name: "Norway",
    nationality: "Norwegian",
  },
  {
    num_code: "512",
    alpha_2_code: "OM",
    alpha_3_code: "OMN",
    en_short_name: "Oman",
    nationality: "Omani",
  },
  {
    num_code: "586",
    alpha_2_code: "PK",
    alpha_3_code: "PAK",
    en_short_name: "Pakistan",
    nationality: "Pakistani",
  },
  {
    num_code: "585",
    alpha_2_code: "PW",
    alpha_3_code: "PLW",
    en_short_name: "Palau",
    nationality: "Palauan",
  },
  {
    num_code: "275",
    alpha_2_code: "PS",
    alpha_3_code: "PSE",
    en_short_name: "Palestine, State of",
    nationality: "Palestinian",
  },
  {
    num_code: "591",
    alpha_2_code: "PA",
    alpha_3_code: "PAN",
    en_short_name: "Panama",
    nationality: "Panamanian",
  },
  {
    num_code: "598",
    alpha_2_code: "PG",
    alpha_3_code: "PNG",
    en_short_name: "Papua New Guinea",
    nationality: "Papua New Guinean, Papuan",
  },
  {
    num_code: "600",
    alpha_2_code: "PY",
    alpha_3_code: "PRY",
    en_short_name: "Paraguay",
    nationality: "Paraguayan",
  },
  {
    num_code: "604",
    alpha_2_code: "PE",
    alpha_3_code: "PER",
    en_short_name: "Peru",
    nationality: "Peruvian",
  },
  {
    num_code: "608",
    alpha_2_code: "PH",
    alpha_3_code: "PHL",
    en_short_name: "Philippines",
    nationality: "Philippine, Filipino",
  },
  {
    num_code: "612",
    alpha_2_code: "PN",
    alpha_3_code: "PCN",
    en_short_name: "Pitcairn",
    nationality: "Pitcairn Island",
  },
  {
    num_code: "616",
    alpha_2_code: "PL",
    alpha_3_code: "POL",
    en_short_name: "Poland",
    nationality: "Polish",
  },
  {
    num_code: "620",
    alpha_2_code: "PT",
    alpha_3_code: "PRT",
    en_short_name: "Portugal",
    nationality: "Portuguese",
  },
  {
    num_code: "630",
    alpha_2_code: "PR(1787)",
    alpha_3_code: "PRI",
    en_short_name: "Puerto Rico",
    nationality: "Puerto Rican",
  },
  {
    num_code: "630",
    alpha_2_code: "PR(1939)",
    alpha_3_code: "PRI",
    en_short_name: "Puerto Rico",
    nationality: "Puerto Rican",
  },
  {
    num_code: "634",
    alpha_2_code: "QA",
    alpha_3_code: "QAT",
    en_short_name: "Qatar",
    nationality: "Qatari",
  },
  {
    num_code: "638",
    alpha_2_code: "RE",
    alpha_3_code: "REU",
    en_short_name: "R\u00e9union",
    nationality: "R\u00e9unionese, R\u00e9unionnais",
  },
  {
    num_code: "642",
    alpha_2_code: "RO",
    alpha_3_code: "ROU",
    en_short_name: "Romania",
    nationality: "Romanian",
  },
  {
    num_code: "643",
    alpha_2_code: "RU",
    alpha_3_code: "RUS",
    en_short_name: "Russian Federation",
    nationality: "Russian",
  },
  {
    num_code: "646",
    alpha_2_code: "RW",
    alpha_3_code: "RWA",
    en_short_name: "Rwanda",
    nationality: "Rwandan",
  },
  {
    num_code: "652",
    alpha_2_code: "BL",
    alpha_3_code: "BLM",
    en_short_name: "Saint Barth\u00e9lemy",
    nationality: "Barth\u00e9lemois",
  },
  {
    num_code: "654",
    alpha_2_code: "SH",
    alpha_3_code: "SHN",
    en_short_name: "Saint Helena, Ascension and Tristan da Cunha",
    nationality: "Saint Helenian",
  },
  {
    num_code: "659",
    alpha_2_code: "KN",
    alpha_3_code: "KNA",
    en_short_name: "Saint Kitts and Nevis",
    nationality: "Kittitian or Nevisian",
  },
  {
    num_code: "662",
    alpha_2_code: "LC",
    alpha_3_code: "LCA",
    en_short_name: "Saint Lucia",
    nationality: "Saint Lucian",
  },
  {
    num_code: "663",
    alpha_2_code: "MF",
    alpha_3_code: "MAF",
    en_short_name: "Saint Martin (French part)",
    nationality: "Saint-Martinoise",
  },
  {
    num_code: "666",
    alpha_2_code: "PM",
    alpha_3_code: "SPM",
    en_short_name: "Saint Pierre and Miquelon",
    nationality: "Saint-Pierrais or Miquelonnais",
  },
  {
    num_code: "670",
    alpha_2_code: "VC",
    alpha_3_code: "VCT",
    en_short_name: "Saint Vincent and the Grenadines",
    nationality: "Saint Vincentian, Vincentian",
  },
  {
    num_code: "882",
    alpha_2_code: "WS",
    alpha_3_code: "WSM",
    en_short_name: "Samoa",
    nationality: "Samoan",
  },
  {
    num_code: "674",
    alpha_2_code: "SM",
    alpha_3_code: "SMR",
    en_short_name: "San Marino",
    nationality: "Sammarinese",
  },
  {
    num_code: "678",
    alpha_2_code: "ST",
    alpha_3_code: "STP",
    en_short_name: "Sao Tome and Principe",
    nationality: "S\u00e3o Tom\u00e9an",
  },
  {
    num_code: "682",
    alpha_2_code: "SA",
    alpha_3_code: "SAU",
    en_short_name: "Saudi Arabia",
    nationality: "Saudi, Saudi Arabian",
  },
  {
    num_code: "686",
    alpha_2_code: "SN",
    alpha_3_code: "SEN",
    en_short_name: "Senegal",
    nationality: "Senegalese",
  },
  {
    num_code: "688",
    alpha_2_code: "RS",
    alpha_3_code: "SRB",
    en_short_name: "Serbia",
    nationality: "Serbian",
  },
  {
    num_code: "690",
    alpha_2_code: "SC",
    alpha_3_code: "SYC",
    en_short_name: "Seychelles",
    nationality: "Seychellois",
  },
  {
    num_code: "694",
    alpha_2_code: "SL",
    alpha_3_code: "SLE",
    en_short_name: "Sierra Leone",
    nationality: "Sierra Leonean",
  },
  {
    num_code: "702",
    alpha_2_code: "SG",
    alpha_3_code: "SGP",
    en_short_name: "Singapore",
    nationality: "Singaporean",
  },
  {
    num_code: "534",
    alpha_2_code: "SX",
    alpha_3_code: "SXM",
    en_short_name: "Sint Maarten (Dutch part)",
    nationality: "Sint Maarten",
  },
  {
    num_code: "703",
    alpha_2_code: "SK",
    alpha_3_code: "SVK",
    en_short_name: "Slovakia",
    nationality: "Slovak",
  },
  {
    num_code: "705",
    alpha_2_code: "SI",
    alpha_3_code: "SVN",
    en_short_name: "Slovenia",
    nationality: "Slovenian, Slovene",
  },
  {
    num_code: "90",
    alpha_2_code: "SB",
    alpha_3_code: "SLB",
    en_short_name: "Solomon Islands",
    nationality: "Solomon Island",
  },
  {
    num_code: "706",
    alpha_2_code: "SO",
    alpha_3_code: "SOM",
    en_short_name: "Somalia",
    nationality: "Somali, Somalian",
  },
  {
    num_code: "710",
    alpha_2_code: "ZA",
    alpha_3_code: "ZAF",
    en_short_name: "South Africa",
    nationality: "South African",
  },
  {
    num_code: "239",
    alpha_2_code: "GS",
    alpha_3_code: "SGS",
    en_short_name: "South Georgia and the South Sandwich Islands",
    nationality: "South Georgia or South Sandwich Islands",
  },
  {
    num_code: "728",
    alpha_2_code: "SS",
    alpha_3_code: "SSD",
    en_short_name: "South Sudan",
    nationality: "South Sudanese",
  },
  {
    num_code: "724",
    alpha_2_code: "ES",
    alpha_3_code: "ESP",
    en_short_name: "Spain",
    nationality: "Spanish",
  },
  {
    num_code: "144",
    alpha_2_code: "LK",
    alpha_3_code: "LKA",
    en_short_name: "Sri Lanka",
    nationality: "Sri Lankan",
  },
  {
    num_code: "729",
    alpha_2_code: "SD",
    alpha_3_code: "SDN",
    en_short_name: "Sudan",
    nationality: "Sudanese",
  },
  {
    num_code: "740",
    alpha_2_code: "SR",
    alpha_3_code: "SUR",
    en_short_name: "Suriname",
    nationality: "Surinamese",
  },
  {
    num_code: "744",
    alpha_2_code: "SJ",
    alpha_3_code: "SJM",
    en_short_name: "Svalbard and Jan Mayen",
    nationality: "Svalbard",
  },
  {
    num_code: "748",
    alpha_2_code: "SZ",
    alpha_3_code: "SWZ",
    en_short_name: "Swaziland",
    nationality: "Swazi",
  },
  {
    num_code: "752",
    alpha_2_code: "SE",
    alpha_3_code: "SWE",
    en_short_name: "Sweden",
    nationality: "Swedish",
  },
  {
    num_code: "756",
    alpha_2_code: "CH",
    alpha_3_code: "CHE",
    en_short_name: "Switzerland",
    nationality: "Swiss",
  },
  {
    num_code: "760",
    alpha_2_code: "SY",
    alpha_3_code: "SYR",
    en_short_name: "Syrian Arab Republic",
    nationality: "Syrian",
  },
  {
    num_code: "158",
    alpha_2_code: "TW",
    alpha_3_code: "TWN",
    en_short_name: "Taiwan, Province of China",
    nationality: "Chinese, Taiwanese",
  },
  {
    num_code: "762",
    alpha_2_code: "TJ",
    alpha_3_code: "TJK",
    en_short_name: "Tajikistan",
    nationality: "Tajikistani",
  },
  {
    num_code: "834",
    alpha_2_code: "TZ",
    alpha_3_code: "TZA",
    en_short_name: "Tanzania, United Republic of",
    nationality: "Tanzanian",
  },
  {
    num_code: "764",
    alpha_2_code: "TH",
    alpha_3_code: "THA",
    en_short_name: "Thailand",
    nationality: "Thai",
  },
  {
    num_code: "626",
    alpha_2_code: "TL",
    alpha_3_code: "TLS",
    en_short_name: "Timor-Leste",
    nationality: "Timorese",
  },
  {
    num_code: "768",
    alpha_2_code: "TG",
    alpha_3_code: "TGO",
    en_short_name: "Togo",
    nationality: "Togolese",
  },
  {
    num_code: "772",
    alpha_2_code: "TK",
    alpha_3_code: "TKL",
    en_short_name: "Tokelau",
    nationality: "Tokelauan",
  },
  {
    num_code: "776",
    alpha_2_code: "TO",
    alpha_3_code: "TON",
    en_short_name: "Tonga",
    nationality: "Tongan",
  },
  {
    num_code: "780",
    alpha_2_code: "TT",
    alpha_3_code: "TTO",
    en_short_name: "Trinidad and Tobago",
    nationality: "Trinidadian or Tobagonian",
  },
  {
    num_code: "788",
    alpha_2_code: "TN",
    alpha_3_code: "TUN",
    en_short_name: "Tunisia",
    nationality: "Tunisian",
  },
  {
    num_code: "792",
    alpha_2_code: "TR",
    alpha_3_code: "TUR",
    en_short_name: "Turkey",
    nationality: "Turkish",
  },
  {
    num_code: "795",
    alpha_2_code: "TM",
    alpha_3_code: "TKM",
    en_short_name: "Turkmenistan",
    nationality: "Turkmen",
  },
  {
    num_code: "796",
    alpha_2_code: "TC",
    alpha_3_code: "TCA",
    en_short_name: "Turks and Caicos Islands",
    nationality: "Turks and Caicos Island",
  },
  {
    num_code: "798",
    alpha_2_code: "TV",
    alpha_3_code: "TUV",
    en_short_name: "Tuvalu",
    nationality: "Tuvaluan",
  },
  {
    num_code: "800",
    alpha_2_code: "UG",
    alpha_3_code: "UGA",
    en_short_name: "Uganda",
    nationality: "Ugandan",
  },
  {
    num_code: "804",
    alpha_2_code: "UA",
    alpha_3_code: "UKR",
    en_short_name: "Ukraine",
    nationality: "Ukrainian",
  },
  {
    num_code: "784",
    alpha_2_code: "AE",
    alpha_3_code: "ARE",
    en_short_name: "United Arab Emirates",
    nationality: "Emirati, Emirian, Emiri",
  },
  {
    num_code: "826",
    alpha_2_code: "GB",
    alpha_3_code: "GBR",
    en_short_name: "United Kingdom of Great Britain and Northern Ireland",
    nationality: "British, UK",
  },
  {
    num_code: "581",
    alpha_2_code: "UM",
    alpha_3_code: "UMI",
    en_short_name: "United States Minor Outlying Islands",
    nationality: "American",
  },
  {
    num_code: "840",
    alpha_2_code: "US",
    alpha_3_code: "USA",
    en_short_name: "United States of America",
    nationality: "American",
  },
  {
    num_code: "858",
    alpha_2_code: "UY",
    alpha_3_code: "URY",
    en_short_name: "Uruguay",
    nationality: "Uruguayan",
  },
  {
    num_code: "860",
    alpha_2_code: "UZ",
    alpha_3_code: "UZB",
    en_short_name: "Uzbekistan",
    nationality: "Uzbekistani, Uzbek",
  },
  {
    num_code: "548",
    alpha_2_code: "VU",
    alpha_3_code: "VUT",
    en_short_name: "Vanuatu",
    nationality: "Ni-Vanuatu, Vanuatuan",
  },
  {
    num_code: "862",
    alpha_2_code: "VE",
    alpha_3_code: "VEN",
    en_short_name: "Venezuela (Bolivarian Republic of)",
    nationality: "Venezuelan",
  },
  {
    num_code: "704",
    alpha_2_code: "VN",
    alpha_3_code: "VNM",
    en_short_name: "Vietnam",
    nationality: "Vietnamese",
  },
  {
    num_code: "92",
    alpha_2_code: "VG",
    alpha_3_code: "VGB",
    en_short_name: "Virgin Islands (British)",
    nationality: "British Virgin Island",
  },
  {
    num_code: "850",
    alpha_2_code: "VI",
    alpha_3_code: "VIR",
    en_short_name: "Virgin Islands (U.S.)",
    nationality: "U.S. Virgin Island",
  },
  {
    num_code: "876",
    alpha_2_code: "WF",
    alpha_3_code: "WLF",
    en_short_name: "Wallis and Futuna",
    nationality: "Wallis and Futuna, Wallisian or Futunan",
  },
  {
    num_code: "732",
    alpha_2_code: "EH",
    alpha_3_code: "ESH",
    en_short_name: "Western Sahara",
    nationality: "Sahrawi, Sahrawian, Sahraouian",
  },
  {
    num_code: "887",
    alpha_2_code: "YE",
    alpha_3_code: "YEM",
    en_short_name: "Yemen",
    nationality: "Yemeni",
  },
  {
    num_code: "894",
    alpha_2_code: "ZM",
    alpha_3_code: "ZMB",
    en_short_name: "Zambia",
    nationality: "Zambian",
  },
  {
    num_code: "716",
    alpha_2_code: "ZW",
    alpha_3_code: "ZWE",
    en_short_name: "Zimbabwe",
    nationality: "Zimbabwean",
  },
];
