export const countriesList = [
  {
    country: "AC",
    dialCode: "+247",
    exampleNumber: "40123",
    countryName: "Ascension Island",
  },
  {
    country: "AD",
    dialCode: "+376",
    exampleNumber: "312345",
    countryName: "Andorra",
  },
  {
    country: "AE",
    dialCode: "+971",
    exampleNumber: "501234567",
    countryName: "United Arab Emirates",
  },
  {
    country: "AF",
    dialCode: "+93",
    exampleNumber: "701234567",
    countryName: "Afghanistan",
  },
  {
    country: "AG",
    dialCode: "+1",
    exampleNumber: "2684641234",
    countryName: "Antigua and Barbuda",
  },
  {
    country: "AI",
    dialCode: "+1",
    exampleNumber: "2642351234",
    countryName: "Anguilla",
  },
  {
    country: "AL",
    dialCode: "+355",
    exampleNumber: "672123456",
    countryName: "Albania",
  },
  {
    country: "AM",
    dialCode: "+374",
    exampleNumber: "77123456",
    countryName: "Armenia",
  },
  {
    country: "AO",
    dialCode: "+244",
    exampleNumber: "923123456",
    countryName: "Angola",
  },
  {
    country: "AR",
    dialCode: "+54",
    exampleNumber: "91123456789",
    countryName: "Argentina",
  },
  {
    country: "AS",
    dialCode: "+1",
    exampleNumber: "6847331234",
    countryName: "American Samoa",
  },
  {
    country: "AT",
    dialCode: "+43",
    exampleNumber: "664123456",
    countryName: "Austria",
  },
  {
    country: "AU",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Australia",
  },
  {
    country: "AW",
    dialCode: "+297",
    exampleNumber: "5601234",
    countryName: "Aruba",
  },
  {
    country: "AX",
    dialCode: "+358",
    exampleNumber: "412345678",
    countryName: "Åland Islands",
  },
  {
    country: "AZ",
    dialCode: "+994",
    exampleNumber: "401234567",
    countryName: "Azerbaijan",
  },
  {
    country: "BA",
    dialCode: "+387",
    exampleNumber: "61123456",
    countryName: "Bosnia and Herzegovina",
  },
  {
    country: "BB",
    dialCode: "+1",
    exampleNumber: "2462501234",
    countryName: "Barbados",
  },
  {
    country: "BD",
    dialCode: "+880",
    exampleNumber: "1812345678",
    countryName: "Bangladesh",
  },
  {
    country: "BE",
    dialCode: "+32",
    exampleNumber: "470123456",
    countryName: "Belgium",
  },
  {
    country: "BF",
    dialCode: "+226",
    exampleNumber: "70123456",
    countryName: "Burkina Faso",
  },
  {
    country: "BG",
    dialCode: "+359",
    exampleNumber: "43012345",
    countryName: "Bulgaria",
  },
  {
    country: "BH",
    dialCode: "+973",
    exampleNumber: "36001234",
    countryName: "Bahrain",
  },
  {
    country: "BI",
    dialCode: "+257",
    exampleNumber: "79561234",
    countryName: "Burundi",
  },
  {
    country: "BJ",
    dialCode: "+229",
    exampleNumber: "0195123456",
    countryName: "Benin",
  },
  {
    country: "BL",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Saint Martin",
  },
  {
    country: "BM",
    dialCode: "+1",
    exampleNumber: "4413701234",
    countryName: "Bermuda",
  },
  {
    country: "BN",
    dialCode: "+673",
    exampleNumber: "7123456",
    countryName: "Brunei Darussalam",
  },
  {
    country: "BO",
    dialCode: "+591",
    exampleNumber: "71234567",
    countryName: "Bolivia",
  },
  {
    country: "BQ",
    dialCode: "+599",
    exampleNumber: "3181234",
    countryName: "Bonaire",
  },
  {
    country: "BR",
    dialCode: "+55",
    exampleNumber: "11961234567",
    countryName: "Brazil",
  },
  {
    country: "BS",
    dialCode: "+1",
    exampleNumber: "2423591234",
    countryName: "Bahamas",
  },
  {
    country: "BT",
    dialCode: "+975",
    exampleNumber: "17123456",
    countryName: "Bhutan",
  },
  {
    country: "BW",
    dialCode: "+267",
    exampleNumber: "71123456",
    countryName: "Botswana",
  },
  {
    country: "BY",
    dialCode: "+375",
    exampleNumber: "294911911",
    countryName: "Belarus",
  },
  {
    country: "BZ",
    dialCode: "+501",
    exampleNumber: "6221234",
    countryName: "Belize",
  },
  {
    country: "CA",
    dialCode: "+1",
    exampleNumber: "5062345678",
    countryName: "Canada",
  },
  {
    country: "CC",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Cocos (Keeling) Islands",
  },
  {
    country: "CD",
    dialCode: "+243",
    exampleNumber: "991234567",
    countryName: "Congo, The Democratic Republic of the",
  },
  {
    country: "CF",
    dialCode: "+236",
    exampleNumber: "70012345",
    countryName: "Central African Republic",
  },
  {
    country: "CG",
    dialCode: "+242",
    exampleNumber: "061234567",
    countryName: "Congo",
  },
  {
    country: "CH",
    dialCode: "+41",
    exampleNumber: "781234567",
    countryName: "Switzerland",
  },
  {
    country: "CI",
    dialCode: "+225",
    exampleNumber: "0123456789",
    countryName: "Cote D&apos;Ivoire",
  },
  {
    country: "CK",
    dialCode: "+682",
    exampleNumber: "71234",
    countryName: "Cook Islands",
  },
  {
    country: "CL",
    dialCode: "+56",
    exampleNumber: "221234567",
    countryName: "Chile",
  },
  {
    country: "CM",
    dialCode: "+237",
    exampleNumber: "671234567",
    countryName: "Cameroon",
  },
  {
    country: "CN",
    dialCode: "+86",
    exampleNumber: "13123456789",
    countryName: "China",
  },
  {
    country: "CO",
    dialCode: "+57",
    exampleNumber: "3211234567",
    countryName: "Colombia",
  },
  {
    country: "CR",
    dialCode: "+506",
    exampleNumber: "83123456",
    countryName: "Costa Rica",
  },
  {
    country: "CU",
    dialCode: "+53",
    exampleNumber: "51234567",
    countryName: "Cuba",
  },
  {
    country: "CV",
    dialCode: "+238",
    exampleNumber: "9911234",
    countryName: "Cape Verde",
  },
  {
    country: "CW",
    dialCode: "+599",
    exampleNumber: "95181234",
    countryName: "Caribbean Netherlands",
  },
  {
    country: "CX",
    dialCode: "+61",
    exampleNumber: "412345678",
    countryName: "Christmas Island",
  },
  {
    country: "CY",
    dialCode: "+357",
    exampleNumber: "96123456",
    countryName: "Cyprus",
  },
  {
    country: "CZ",
    dialCode: "+420",
    exampleNumber: "601123456",
    countryName: "Czech Republic",
  },
  {
    country: "DE",
    dialCode: "+49",
    exampleNumber: "15123456789",
    countryName: "Germany",
  },
  {
    country: "DJ",
    dialCode: "+253",
    exampleNumber: "77831001",
    countryName: "Djibouti",
  },
  {
    country: "DK",
    dialCode: "+45",
    exampleNumber: "34412345",
    countryName: "Denmark",
  },
  {
    country: "DM",
    dialCode: "+1",
    exampleNumber: "7672251234",
    countryName: "Dominica",
  },
  {
    country: "DO",
    dialCode: "+1",
    exampleNumber: "8092345678",
    countryName: "Dominican Republic",
  },
  {
    country: "DZ",
    dialCode: "+213",
    exampleNumber: "551234567",
    countryName: "Algeria",
  },
  {
    country: "EC",
    dialCode: "+593",
    exampleNumber: "991234567",
    countryName: "Ecuador",
  },
  {
    country: "EE",
    dialCode: "+372",
    exampleNumber: "51234567",
    countryName: "Estonia",
  },
  {
    country: "EG",
    dialCode: "+20",
    exampleNumber: "1001234567",
    countryName: "Egypt",
  },
  {
    country: "EH",
    dialCode: "+212",
    exampleNumber: "650123456",
    countryName: "Western Sahara",
  },
  {
    country: "ER",
    dialCode: "+291",
    exampleNumber: "7123456",
    countryName: "Eritrea",
  },
  {
    country: "ES",
    dialCode: "+34",
    exampleNumber: "612345678",
    countryName: "Spain",
  },
  {
    country: "ET",
    dialCode: "+251",
    exampleNumber: "911234567",
    countryName: "Ethiopia",
  },
  {
    country: "FI",
    dialCode: "+358",
    exampleNumber: "412345678",
    countryName: "Finland",
  },
  {
    country: "FJ",
    dialCode: "+679",
    exampleNumber: "7012345",
    countryName: "Fiji",
  },
  {
    country: "FK",
    dialCode: "+500",
    exampleNumber: "51234",
    countryName: "Falkland Islands (Malvinas)",
  },
  {
    country: "FM",
    dialCode: "+691",
    exampleNumber: "3501234",
    countryName: "Micronesia, Federated States of",
  },
  {
    country: "FO",
    dialCode: "+298",
    exampleNumber: "211234",
    countryName: "Faroe Islands",
  },
  {
    country: "FR",
    dialCode: "+33",
    exampleNumber: "612345678",
    countryName: "France",
  },
  {
    country: "GA",
    dialCode: "+241",
    exampleNumber: "06031234",
    countryName: "Gabon",
  },
  {
    country: "GB",
    dialCode: "+44",
    exampleNumber: "7400123456",
    countryName: "United Kingdom",
  },
  {
    country: "GD",
    dialCode: "+1",
    exampleNumber: "4734031234",
    countryName: "Grenada",
  },
  {
    country: "GE",
    dialCode: "+995",
    exampleNumber: "555123456",
    countryName: "Georgia",
  },
  {
    country: "GF",
    dialCode: "+594",
    exampleNumber: "694201234",
    countryName: "French Guiana",
  },
  {
    country: "GG",
    dialCode: "+44",
    exampleNumber: "7781123456",
    countryName: "Guernsey",
  },
  {
    country: "GH",
    dialCode: "+233",
    exampleNumber: "231234567",
    countryName: "Ghana",
  },
  {
    country: "GI",
    dialCode: "+350",
    exampleNumber: "57123456",
    countryName: "Gibraltar",
  },
  {
    country: "GL",
    dialCode: "+299",
    exampleNumber: "221234",
    countryName: "Greenland",
  },
  {
    country: "GM",
    dialCode: "+220",
    exampleNumber: "3012345",
    countryName: "Gambia",
  },
  {
    country: "GN",
    dialCode: "+224",
    exampleNumber: "601123456",
    countryName: "Guinea",
  },
  {
    country: "GP",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Guadeloupe",
  },
  {
    country: "GQ",
    dialCode: "+240",
    exampleNumber: "222123456",
    countryName: "Equatorial Guinea",
  },
  {
    country: "GR",
    dialCode: "+30",
    exampleNumber: "6912345678",
    countryName: "Greece",
  },
  {
    country: "GT",
    dialCode: "+502",
    exampleNumber: "51234567",
    countryName: "Guatemala",
  },
  {
    country: "GU",
    dialCode: "+1",
    exampleNumber: "6713001234",
    countryName: "Guam",
  },
  {
    country: "GW",
    dialCode: "+245",
    exampleNumber: "955012345",
    countryName: "Guinea-Bissau",
  },
  {
    country: "GY",
    dialCode: "+592",
    exampleNumber: "6091234",
    countryName: "Guyana",
  },
  {
    country: "HK",
    dialCode: "+852",
    exampleNumber: "51234567",
    countryName: "Hong Kong",
  },
  {
    country: "HN",
    dialCode: "+504",
    exampleNumber: "91234567",
    countryName: "Honduras",
  },
  {
    country: "HR",
    dialCode: "+385",
    exampleNumber: "921234567",
    countryName: "Croatia",
  },
  {
    country: "HT",
    dialCode: "+509",
    exampleNumber: "34101234",
    countryName: "Haiti",
  },
  {
    country: "HU",
    dialCode: "+36",
    exampleNumber: "201234567",
    countryName: "Hungary",
  },
  {
    country: "ID",
    dialCode: "+62",
    exampleNumber: "812345678",
    countryName: "Indonesia",
  },
  {
    country: "IE",
    dialCode: "+353",
    exampleNumber: "850123456",
    countryName: "Ireland",
  },
  {
    country: "IL",
    dialCode: "+972",
    exampleNumber: "502345678",
    countryName: "Israel",
  },
  {
    country: "IM",
    dialCode: "+44",
    exampleNumber: "7924123456",
    countryName: "Isle of Man",
  },
  {
    country: "IN",
    dialCode: "+91",
    exampleNumber: "8123456789",
    countryName: "India",
  },
  {
    country: "IO",
    dialCode: "+246",
    exampleNumber: "3801234",
    countryName: "British Indian Ocean Territory",
  },
  {
    country: "IQ",
    dialCode: "+964",
    exampleNumber: "7912345678",
    countryName: "Iraq",
  },
  {
    country: "IR",
    dialCode: "+98",
    exampleNumber: "9123456789",
    countryName: "Iran",
  },
  {
    country: "IS",
    dialCode: "+354",
    exampleNumber: "6111234",
    countryName: "Iceland",
  },
  {
    country: "IT",
    dialCode: "+39",
    exampleNumber: "3123456789",
    countryName: "Italy",
  },
  {
    country: "JE",
    dialCode: "+44",
    exampleNumber: "7797712345",
    countryName: "Jersey",
  },
  {
    country: "JM",
    dialCode: "+1",
    exampleNumber: "8762101234",
    countryName: "Jamaica",
  },
  {
    country: "JO",
    dialCode: "+962",
    exampleNumber: "790123456",
    countryName: "Jordan",
  },
  {
    country: "JP",
    dialCode: "+81",
    exampleNumber: "9012345678",
    countryName: "Japan",
  },
  {
    country: "KE",
    dialCode: "+254",
    exampleNumber: "712123456",
    countryName: "Kenya",
  },
  {
    country: "KG",
    dialCode: "+996",
    exampleNumber: "700123456",
    countryName: "Kyrgyzstan",
  },
  {
    country: "KH",
    dialCode: "+855",
    exampleNumber: "91234567",
    countryName: "Cambodia",
  },
  {
    country: "KI",
    dialCode: "+686",
    exampleNumber: "72001234",
    countryName: "Kiribati",
  },
  {
    country: "KM",
    dialCode: "+269",
    exampleNumber: "3212345",
    countryName: "Comoros",
  },
  {
    country: "KN",
    dialCode: "+1",
    exampleNumber: "8697652917",
    countryName: "Saint Kitts and Nevis",
  },
  {
    country: "KP",
    dialCode: "+850",
    exampleNumber: "1921234567",
    countryName: "Korea, Democratic People&apos;S Republic of",
  },
  {
    country: "KR",
    dialCode: "+82",
    countryName: "South Korea",
  },
  {
    country: "KW",
    dialCode: "+965",
    exampleNumber: "50012345",
    countryName: "Kuwait",
  },
  {
    country: "KY",
    dialCode: "+1",
    exampleNumber: "3453231234",
    countryName: "Cayman Islands",
  },
  {
    country: "KZ",
    dialCode: "+7",
    exampleNumber: "7710009998",
    countryName: "Kazakhstan",
  },
  {
    country: "LA",
    dialCode: "+856",
    exampleNumber: "2023123456",
    countryName: "Lao People&apos;S Democratic Republic",
  },
  {
    country: "LB",
    dialCode: "+961",
    exampleNumber: "71123456",
    countryName: "Lebanon",
  },
  {
    country: "LC",
    dialCode: "+1",
    exampleNumber: "7582845678",
    countryName: "Saint Lucia",
  },
  {
    country: "LI",
    dialCode: "+423",
    exampleNumber: "660234567",
    countryName: "Liechtenstein",
  },
  {
    country: "LK",
    dialCode: "+94",
    exampleNumber: "712345678",
    countryName: "Sri Lanka",
  },
  {
    country: "LR",
    dialCode: "+231",
    exampleNumber: "770123456",
    countryName: "Liberia",
  },
  {
    country: "LS",
    dialCode: "+266",
    exampleNumber: "50123456",
    countryName: "Lesotho",
  },
  {
    country: "LT",
    dialCode: "+370",
    exampleNumber: "61234567",
    countryName: "Lithuania",
  },
  {
    country: "LU",
    dialCode: "+352",
    exampleNumber: "628123456",
    countryName: "Luxembourg",
  },
  {
    country: "LV",
    dialCode: "+371",
    exampleNumber: "21234567",
    countryName: "Latvia",
  },
  {
    country: "LY",
    dialCode: "+218",
    exampleNumber: "912345678",
    countryName: "Libyan Arab Jamahiriya",
  },
  {
    country: "MA",
    dialCode: "+212",
    exampleNumber: "650123456",
    countryName: "Morocco",
  },
  {
    country: "MC",
    dialCode: "+377",
    exampleNumber: "612345678",
    countryName: "Monaco",
  },
  {
    country: "MD",
    dialCode: "+373",
    exampleNumber: "62112345",
    countryName: "Moldova, Republic of",
  },
  {
    country: "ME",
    dialCode: "+382",
    exampleNumber: "67622901",
    countryName: "Montenegro",
  },
  {
    country: "MF",
    dialCode: "+590",
    exampleNumber: "690001234",
    countryName: "Saint-Barthélemy",
  },
  {
    country: "MG",
    dialCode: "+261",
    exampleNumber: "321234567",
    countryName: "Madagascar",
  },
  {
    country: "MH",
    dialCode: "+692",
    exampleNumber: "2351234",
    countryName: "Marshall Islands",
  },
  {
    country: "MK",
    dialCode: "+389",
    exampleNumber: "72345678",
    countryName: "Macedonia, The Former Yugoslav Republic of",
  },
  {
    country: "ML",
    dialCode: "+223",
    exampleNumber: "65012345",
    countryName: "Mali",
  },
  {
    country: "MM",
    dialCode: "+95",
    exampleNumber: "92123456",
    countryName: "Myanmar",
  },
  {
    country: "MN",
    dialCode: "+976",
    exampleNumber: "88123456",
    countryName: "Mongolia",
  },
  {
    country: "MO",
    dialCode: "+853",
    exampleNumber: "66123456",
    countryName: "Macao",
  },
  {
    country: "MP",
    dialCode: "+1",
    exampleNumber: "6702345678",
    countryName: "Northern Mariana Islands",
  },
  {
    country: "MQ",
    dialCode: "+596",
    exampleNumber: "696201234",
    countryName: "Martinique",
  },
  {
    country: "MR",
    dialCode: "+222",
    exampleNumber: "22123456",
    countryName: "Mauritania",
  },
  {
    country: "MS",
    dialCode: "+1",
    exampleNumber: "6644923456",
    countryName: "Montserrat",
  },
  {
    country: "MT",
    dialCode: "+356",
    exampleNumber: "96961234",
    countryName: "Malta",
  },
  {
    country: "MU",
    dialCode: "+230",
    exampleNumber: "52512345",
    countryName: "Mauritius",
  },
  {
    country: "MV",
    dialCode: "+960",
    exampleNumber: "7712345",
    countryName: "Maldives",
  },
  {
    country: "MW",
    dialCode: "+265",
    exampleNumber: "991234567",
    countryName: "Malawi",
  },
  {
    country: "MX",
    dialCode: "+52",
    exampleNumber: "2221234567",
    countryName: "Mexico",
  },
  {
    country: "MY",
    dialCode: "+60",
    exampleNumber: "123456789",
    countryName: "Malaysia",
  },
  {
    country: "MZ",
    dialCode: "+258",
    exampleNumber: "821234567",
    countryName: "Mozambique",
  },
  {
    country: "NA",
    dialCode: "+264",
    exampleNumber: "811234567",
    countryName: "Namibia",
  },
  {
    country: "NC",
    dialCode: "+687",
    exampleNumber: "751234",
    countryName: "New Caledonia",
  },
  {
    country: "NE",
    dialCode: "+227",
    exampleNumber: "93123456",
    countryName: "Niger",
  },
  {
    country: "NF",
    dialCode: "+672",
    exampleNumber: "381234",
    countryName: "Norfolk Island",
  },
  {
    country: "NG",
    dialCode: "+234",
    exampleNumber: "8021234567",
    countryName: "Nigeria",
  },
  {
    country: "NI",
    dialCode: "+505",
    exampleNumber: "81234567",
    countryName: "Nicaragua",
  },
  {
    country: "NL",
    dialCode: "+31",
    exampleNumber: "612345678",
    countryName: "Netherlands",
  },
  {
    country: "NO",
    dialCode: "+47",
    exampleNumber: "40612345",
    countryName: "Norway",
  },
  {
    country: "NP",
    dialCode: "+977",
    exampleNumber: "9841234567",
    countryName: "Nepal",
  },
  {
    country: "NR",
    dialCode: "+674",
    exampleNumber: "5551234",
    countryName: "Nauru",
  },
  {
    country: "NU",
    dialCode: "+683",
    exampleNumber: "8884012",
    countryName: "Niue",
  },
  {
    country: "NZ",
    dialCode: "+64",
    exampleNumber: "211234567",
    countryName: "New Zealand",
  },
  {
    country: "OM",
    dialCode: "+968",
    exampleNumber: "92123456",
    countryName: "Oman",
  },
  {
    country: "PA",
    dialCode: "+507",
    exampleNumber: "61234567",
    countryName: "Panama",
  },
  {
    country: "PE",
    dialCode: "+51",
    exampleNumber: "912345678",
    countryName: "Peru",
  },
  {
    country: "PF",
    dialCode: "+689",
    exampleNumber: "87123456",
    countryName: "French Polynesia",
  },
  {
    country: "PG",
    dialCode: "+675",
    exampleNumber: "70123456",
    countryName: "Papua New Guinea",
  },
  {
    country: "PH",
    dialCode: "+63",
    exampleNumber: "9051234567",
    countryName: "Philippines",
  },
  {
    country: "PK",
    dialCode: "+92",
    exampleNumber: "3012345678",
    countryName: "Pakistan",
  },
  {
    country: "PL",
    dialCode: "+48",
    exampleNumber: "512345678",
    countryName: "Poland",
  },
  {
    country: "PM",
    dialCode: "+508",
    exampleNumber: "551234",
    countryName: "Saint Pierre and Miquelon",
  },
  {
    country: "PR",
    dialCode: "+1",
    exampleNumber: "7872345678",
    countryName: "Puerto Rico ",
  },
  {
    country: "PS",
    dialCode: "+970",
    exampleNumber: "599123456",
    countryName: "Palestinian Territory, Occupied",
  },
  {
    country: "PT",
    dialCode: "+351",
    exampleNumber: "912345678",
    countryName: "Portugal",
  },
  {
    country: "PW",
    dialCode: "+680",
    exampleNumber: "6201234",
    countryName: "Palau",
  },
  {
    country: "PY",
    dialCode: "+595",
    exampleNumber: "961456789",
    countryName: "Paraguay",
  },
  {
    country: "QA",
    dialCode: "+974",
    exampleNumber: "33123456",
    countryName: "Qatar",
  },
  {
    country: "RE",
    dialCode: "+262",
    exampleNumber: "692123456",
    countryName: "Reunion",
  },
  {
    country: "RO",
    dialCode: "+40",
    exampleNumber: "712034567",
    countryName: "Romania",
  },
  {
    country: "RS",
    dialCode: "+381",
    exampleNumber: "601234567",
    countryName: "Serbia",
  },
  {
    country: "RU",
    dialCode: "+7",
    exampleNumber: "9123456789",
    countryName: "Russian Federation",
  },
  {
    country: "RW",
    dialCode: "+250",
    exampleNumber: "720123456",
    countryName: "RWANDA",
  },
  {
    country: "SA",
    dialCode: "+966",
    exampleNumber: "512345678",
    countryName: "Saudi Arabia",
  },
  {
    country: "SB",
    dialCode: "+677",
    exampleNumber: "7421234",
    countryName: "Solomon Islands",
  },
  {
    country: "SC",
    dialCode: "+248",
    exampleNumber: "2510123",
    countryName: "Seychelles",
  },
  {
    country: "SD",
    dialCode: "+249",
    exampleNumber: "911231234",
    countryName: "Sudan",
  },
  {
    country: "SE",
    dialCode: "+46",
    exampleNumber: "701234567",
    countryName: "Sweden",
  },
  {
    country: "SG",
    dialCode: "+65",
    exampleNumber: "81234567",
    countryName: "Singapore",
  },
  {
    country: "SH",
    dialCode: "+290",
    exampleNumber: "51234",
    countryName: "Saint Helena",
  },
  {
    country: "SI",
    dialCode: "+386",
    exampleNumber: "31234567",
    countryName: "Slovenia",
  },
  {
    country: "SJ",
    dialCode: "+47",
    exampleNumber: "41234567",
    countryName: "Svalbard and Jan Mayen",
  },
  {
    country: "SK",
    dialCode: "+421",
    exampleNumber: "912123456",
    countryName: "Slovakia",
  },
  {
    country: "SL",
    dialCode: "+232",
    exampleNumber: "25123456",
    countryName: "Sierra Leone",
  },
  {
    country: "SM",
    dialCode: "+378",
    exampleNumber: "66661212",
    countryName: "San Marino",
  },
  {
    country: "SN",
    dialCode: "+221",
    exampleNumber: "701234567",
    countryName: "Senegal",
  },
  {
    country: "SO",
    dialCode: "+252",
    exampleNumber: "71123456",
    countryName: "Somalia",
  },
  {
    country: "SR",
    dialCode: "+597",
    exampleNumber: "7412345",
    countryName: "Surikey:1,name",
  },
  {
    country: "SS",
    dialCode: "+211",
    exampleNumber: "977123456",
    countryName: "South Sudan",
  },
  {
    country: "ST",
    dialCode: "+239",
    exampleNumber: "9812345",
    countryName: "Sao Tome and Principe",
  },
  {
    country: "SV",
    dialCode: "+503",
    exampleNumber: "70123456",
    countryName: "El Salvador",
  },
  {
    country: "SX",
    dialCode: "+1",
    exampleNumber: "7215205678",
    countryName: "Sint Maarten ",
  },
  {
    country: "SY",
    dialCode: "+963",
    exampleNumber: "944567890",
    countryName: "Syrian Arab Republic",
  },
  {
    country: "SZ",
    dialCode: "+268",
    exampleNumber: "76123456",
    countryName: "Swaziland",
  },
  {
    country: "TA",
    dialCode: "+290",
    exampleNumber: "8999",
    countryName: "Tristan da Cunha",
  },
  {
    country: "TC",
    dialCode: "+1",
    exampleNumber: "6492311234",
    countryName: "Turks and Caicos Islands",
  },
  {
    country: "TD",
    dialCode: "+235",
    exampleNumber: "63012345",
    countryName: "Chad",
  },
  {
    country: "TG",
    dialCode: "+228",
    exampleNumber: "90112345",
    countryName: "Togo",
  },
  {
    country: "TH",
    dialCode: "+66",
    exampleNumber: "812345678",
    countryName: "Thailand",
  },
  {
    country: "TJ",
    dialCode: "+992",
    exampleNumber: "917123456",
    countryName: "Tajikistan",
  },
  {
    country: "TK",
    dialCode: "+690",
    exampleNumber: "7290",
    countryName: "Tokelau",
  },
  {
    country: "TL",
    dialCode: "+670",
    exampleNumber: "77212345",
    countryName: "Timor-Leste",
  },
  {
    country: "TM",
    dialCode: "+993",
    exampleNumber: "66123456",
    countryName: "Turkmenistan",
  },
  {
    country: "TN",
    dialCode: "+216",
    exampleNumber: "20123456",
    countryName: "Tunisia",
  },
  {
    country: "TO",
    dialCode: "+676",
    exampleNumber: "7715123",
    countryName: "Tonga",
  },
  {
    country: "TR",
    dialCode: "+90",
    exampleNumber: "5012345678",
    countryName: "Turkey",
  },
  {
    country: "TT",
    dialCode: "+1",
    exampleNumber: "8682911234",
    countryName: "Trinidad and Tobago",
  },
  {
    country: "TV",
    dialCode: "+688",
    exampleNumber: "901234",
    countryName: "Tuvalu",
  },
  {
    country: "TW",
    dialCode: "+886",
    exampleNumber: "912345678",
    countryName: "Taiwan, Province of China",
  },
  {
    country: "TZ",
    dialCode: "+255",
    exampleNumber: "621234567",
    countryName: "Tanzania, United Republic of",
  },
  {
    country: "UA",
    dialCode: "+380",
    exampleNumber: "501234567",
    countryName: "Ukraine",
  },
  {
    country: "UG",
    dialCode: "+256",
    exampleNumber: "712345678",
    countryName: "Uganda",
  },
  {
    country: "US",
    dialCode: "+1",
    exampleNumber: "2015550123",
    countryName: "United States of America",
  },
  {
    country: "UY",
    dialCode: "+598",
    exampleNumber: "94231234",
    countryName: "Uruguay",
  },
  {
    country: "UZ",
    dialCode: "+998",
    exampleNumber: "912345678",
    countryName: "Uzbekistan",
  },
  {
    country: "VA",
    dialCode: "+39",
    exampleNumber: "3123456789",
    countryName: "Holy See (Vatican City State)",
  },
  {
    country: "VC",
    dialCode: "+1",
    exampleNumber: "7844301234",
    countryName: "Saint Vincent and the Grenadines",
  },
  {
    country: "VE",
    dialCode: "+58",
    exampleNumber: "4121234567",
    countryName: "Venezuela",
  },
  {
    country: "VG",
    dialCode: "+1",
    exampleNumber: "2843001234",
    countryName: "Virgin Islands, British",
  },
  {
    country: "VI",
    dialCode: "+1",
    exampleNumber: "3406421234",
    countryName: "Virgin Islands, U.S.",
  },
  {
    country: "VN",
    dialCode: "+84",
    exampleNumber: "912345678",
    countryName: "Viet Nam",
  },
  {
    country: "VU",
    dialCode: "+678",
    exampleNumber: "5912345",
    countryName: "Vanuatu",
  },
  {
    country: "WF",
    dialCode: "+681",
    exampleNumber: "821234",
    countryName: "Wallis and Futuna",
  },
  {
    country: "WS",
    dialCode: "+685",
    exampleNumber: "7212345",
    countryName: "Samoa",
  },
  {
    country: "XK",
    dialCode: "+383",
    exampleNumber: "43201234",
    countryName: "Kosovo",
  },
  {
    country: "YE",
    dialCode: "+967",
    exampleNumber: "712345678",
    countryName: "Yemen",
  },
  {
    country: "YT",
    dialCode: "+262",
    exampleNumber: "639012345",
    countryName: "Mayotte",
  },
  {
    country: "ZA",
    dialCode: "+27",
    exampleNumber: "711234567",
    countryName: "South Africa",
  },
  {
    country: "ZM",
    dialCode: "+260",
    exampleNumber: "955123456",
    countryName: "Zambia",
  },
  {
    country: "ZW",
    dialCode: "+263",
    exampleNumber: "712345678",
    countryName: "Zimbabwe",
  },
];
